import type {
  AnuncioMarketplace,
  CategoriaForum,
  Corrida,
  Equipa,
  Evento,
  Noticia,
  Patrocinador,
  Piloto,
  TopicoForum,
  Video,
} from "./types";

export const TEMPORADA = 2026;

export const SOCIAIS = {
  instagram: "https://www.instagram.com/motobox_angola",
  facebook: "https://www.facebook.com/motoboxangola",
  youtube: "https://www.youtube.com/@motoboxangola",
  whatsapp: "https://wa.me/244923000000",
  email: "geral@motobox.ao",
  telefone: "+244 923 000 000",
};

/* ============================================================
   EVENTOS / CALENDÁRIO
   ============================================================ */

export const eventos: Evento[] = [
  {
    slug: "gp-luanda-abertura",
    titulo: "GP de Luanda — Abertura da Temporada",
    disciplina: "Motocross",
    ronda: 1,
    temporada: 2026,
    circuito: "Circuito do Kilamba",
    provincia: "Luanda",
    localidade: "Kilamba Kiaxi",
    dataInicio: "2026-03-14T08:00:00+01:00",
    dataFim: "2026-03-15T18:00:00+01:00",
    estado: "concluido",
    imagem: "kilamba",
    resumo:
      "A temporada arranca no traçado mais rápido do país, com 32 pilotos inscritos nas categorias MX1, MX2 e Júnior.",
    descricao:
      "O Circuito do Kilamba abre oficialmente o Campeonato Nacional de Motocross 2026. Traçado de terra batida com secções de areia solta, três saltos duplos e uma tabletop de 22 metros que costuma decidir corridas. Zona de público com bancada coberta e área de restauração.",
    organizador: "Federação Angolana de Motociclismo",
    horarios: [
      { dia: "Sábado", hora: "08:00", sessao: "Verificações técnicas" },
      { dia: "Sábado", hora: "10:30", sessao: "Treinos livres MX2" },
      { dia: "Sábado", hora: "12:00", sessao: "Treinos livres MX1" },
      { dia: "Sábado", hora: "15:00", sessao: "Qualificação" },
      { dia: "Domingo", hora: "09:00", sessao: "Warm-up" },
      { dia: "Domingo", hora: "11:00", sessao: "Manga 1 — MX2" },
      { dia: "Domingo", hora: "12:15", sessao: "Manga 1 — MX1" },
      { dia: "Domingo", hora: "15:00", sessao: "Manga 2 — MX2" },
      { dia: "Domingo", hora: "16:15", sessao: "Manga 2 — MX1" },
      { dia: "Domingo", hora: "17:30", sessao: "Cerimónia do pódio" },
    ],
    distanciaVolta: "1,8 km",
    numeroVoltas: 16,
    recordeVolta: { piloto: "Nelson Kiala", tempo: "1:52.340", ano: 2025 },
  },
  {
    slug: "enduro-benguela",
    titulo: "Enduro do Litoral — Benguela",
    disciplina: "Enduro",
    ronda: 2,
    temporada: 2026,
    circuito: "Percurso da Restinga",
    provincia: "Benguela",
    localidade: "Lobito",
    dataInicio: "2026-04-18T07:00:00+01:00",
    dataFim: "2026-04-19T17:00:00+01:00",
    estado: "concluido",
    imagem: "benguela",
    resumo:
      "84 km de percurso misto entre a restinga do Lobito e as encostas da Catumbela. A prova mais dura do calendário.",
    descricao:
      "Prova de enduro em formato de dois dias, com três especiais cronometradas por dia. O percurso alterna areia da restinga, leito seco de rio e trilhos de montanha. Assistência autorizada apenas no parque fechado da Catumbela.",
    organizador: "Moto Clube de Benguela",
    horarios: [
      { dia: "Sábado", hora: "07:00", sessao: "Parque fechado abre" },
      { dia: "Sábado", hora: "08:30", sessao: "Partida — Especial 1" },
      { dia: "Sábado", hora: "13:00", sessao: "Especial 2" },
      { dia: "Sábado", hora: "16:00", sessao: "Especial 3" },
      { dia: "Domingo", hora: "08:30", sessao: "Especial 4" },
      { dia: "Domingo", hora: "12:30", sessao: "Especial 5" },
      { dia: "Domingo", hora: "15:00", sessao: "Especial final" },
      { dia: "Domingo", hora: "17:00", sessao: "Pódio e entrega de prémios" },
    ],
    distanciaVolta: "84 km",
  },
  {
    slug: "gp-huila-lubango",
    titulo: "GP da Huíla — Lubango",
    disciplina: "Motocross",
    ronda: 3,
    temporada: 2026,
    circuito: "Circuito da Tundavala",
    provincia: "Huíla",
    localidade: "Lubango",
    dataInicio: "2026-06-13T08:00:00+01:00",
    dataFim: "2026-06-14T18:00:00+01:00",
    estado: "concluido",
    imagem: "lubango",
    resumo:
      "A 1.700 m de altitude, o traçado da Tundavala testa motores e pulmões. Terreno duro e público recorde.",
    descricao:
      "O circuito mais alto do calendário nacional. A altitude reduz a potência dos motores em cerca de 12%, obrigando a afinações específicas. Traçado técnico, com uma descida de 40 metros de desnível e uma zona de whoops que separa o pelotão.",
    organizador: "Associação Motociclista da Huíla",
    horarios: [
      { dia: "Sábado", hora: "09:00", sessao: "Treinos livres" },
      { dia: "Sábado", hora: "14:00", sessao: "Qualificação" },
      { dia: "Domingo", hora: "10:30", sessao: "Manga 1" },
      { dia: "Domingo", hora: "15:00", sessao: "Manga 2" },
      { dia: "Domingo", hora: "17:00", sessao: "Pódio" },
    ],
    distanciaVolta: "2,1 km",
    numeroVoltas: 14,
    recordeVolta: { piloto: "Bruno Tchipa", tempo: "2:08.910", ano: 2024 },
  },
  {
    slug: "passeio-solidario-cabinda",
    titulo: "Passeio Solidário de Cabinda",
    disciplina: "Solidária",
    temporada: 2026,
    circuito: "Cabinda — Buco-Zau",
    provincia: "Cabinda",
    localidade: "Cabinda",
    dataInicio: "2026-08-09T07:30:00+01:00",
    dataFim: "2026-08-09T16:00:00+01:00",
    estado: "concluido",
    imagem: "cabinda",
    resumo:
      "Mais de 120 motas percorreram 90 km para entregar material escolar a três escolas do município de Buco-Zau.",
    descricao:
      "Iniciativa anual que junta clubes de todo o país numa acção de solidariedade. A inscrição consiste na entrega de material escolar, que é distribuído no final do percurso. Percurso aberto a todas as cilindradas.",
    organizador: "Motobox Angola + Clube Motard de Cabinda",
    horarios: [
      { dia: "Domingo", hora: "07:30", sessao: "Concentração e pequeno-almoço" },
      { dia: "Domingo", hora: "09:00", sessao: "Partida" },
      { dia: "Domingo", hora: "12:00", sessao: "Chegada a Buco-Zau e entrega" },
      { dia: "Domingo", hora: "14:00", sessao: "Almoço convívio" },
      { dia: "Domingo", hora: "16:00", sessao: "Regresso" },
    ],
  },
  {
    slug: "gp-namibe-dunas",
    titulo: "GP do Namibe — Corrida das Dunas",
    disciplina: "Rally",
    ronda: 4,
    temporada: 2026,
    circuito: "Dunas do Namibe",
    provincia: "Namibe",
    localidade: "Moçâmedes",
    dataInicio: "2026-10-10T06:00:00+01:00",
    dataFim: "2026-10-11T18:00:00+01:00",
    estado: "bilhetes-abertos",
    imagem: "namibe",
    resumo:
      "Rally-raid de dois dias nas dunas do deserto do Namibe. 240 km de navegação por roadbook.",
    descricao:
      "A prova mais espetacular do calendário angolano. Dois dias de rally-raid nas dunas costeiras do Namibe, com navegação por roadbook e etapas de 120 km cada. Zona de espectadores no acampamento de partida, com ecrã gigante e transmissão em direto das câmaras de bordo.",
    organizador: "Federação Angolana de Motociclismo",
    horarios: [
      { dia: "Sábado", hora: "06:00", sessao: "Briefing e entrega de roadbook" },
      { dia: "Sábado", hora: "07:30", sessao: "Partida — Etapa 1" },
      { dia: "Sábado", hora: "16:00", sessao: "Chegada e parque fechado" },
      { dia: "Domingo", hora: "07:30", sessao: "Partida — Etapa 2" },
      { dia: "Domingo", hora: "15:30", sessao: "Chegada" },
      { dia: "Domingo", hora: "18:00", sessao: "Pódio e jantar de encerramento" },
    ],
    distanciaVolta: "240 km (total)",
    bilhetes: [
      {
        id: "geral",
        nome: "Geral",
        descricao: "Acesso à zona de público do acampamento de partida e chegada, nos dois dias.",
        preco: 5000,
        disponiveis: 1400,
        beneficios: ["Acesso 2 dias", "Zona de restauração", "Ecrã gigante"],
      },
      {
        id: "tribuna",
        nome: "Tribuna Coberta",
        descricao: "Lugar sentado na bancada coberta com vista sobre a duna de partida.",
        preco: 12000,
        disponiveis: 260,
        beneficios: [
          "Acesso 2 dias",
          "Lugar sentado numerado",
          "Bancada coberta",
          "Programa oficial impresso",
          "Bar exclusivo",
        ],
        destaque: true,
      },
      {
        id: "paddock",
        nome: "Paddock Pass",
        descricao: "Tribuna coberta mais acesso guiado ao parque de assistência e à zona de partida.",
        preco: 28000,
        disponiveis: 60,
        beneficios: [
          "Tudo do Tribuna Coberta",
          "Visita guiada ao paddock",
          "Encontro com pilotos",
          "Almoço nos dois dias",
          "Kit oficial Motobox",
        ],
      },
    ],
  },
  {
    slug: "gp-huambo-final",
    titulo: "GP do Huambo — Final do Campeonato",
    disciplina: "Motocross",
    ronda: 5,
    temporada: 2026,
    circuito: "Circuito da Caála",
    provincia: "Huambo",
    localidade: "Caála",
    dataInicio: "2026-11-21T08:00:00+01:00",
    dataFim: "2026-11-22T19:00:00+01:00",
    estado: "bilhetes-abertos",
    imagem: "huambo",
    resumo:
      "A ronda que decide o título nacional. Apenas 14 pontos separam os três primeiros classificados.",
    descricao:
      "Final da temporada 2026 no traçado da Caála, remodelado este ano com uma nova secção de saltos e uma bancada com capacidade para 3.000 pessoas. A pontuação a dobrar nesta ronda mantém o campeonato em aberto até à última manga.",
    organizador: "Federação Angolana de Motociclismo",
    horarios: [
      { dia: "Sábado", hora: "08:00", sessao: "Verificações técnicas" },
      { dia: "Sábado", hora: "10:00", sessao: "Treinos livres MX2" },
      { dia: "Sábado", hora: "11:30", sessao: "Treinos livres MX1" },
      { dia: "Sábado", hora: "14:30", sessao: "Qualificação MX2" },
      { dia: "Sábado", hora: "16:00", sessao: "Qualificação MX1" },
      { dia: "Domingo", hora: "09:30", sessao: "Warm-up" },
      { dia: "Domingo", hora: "11:00", sessao: "Manga 1 — MX2" },
      { dia: "Domingo", hora: "12:30", sessao: "Manga 1 — MX1" },
      { dia: "Domingo", hora: "15:30", sessao: "Manga 2 — MX2" },
      { dia: "Domingo", hora: "17:00", sessao: "Manga 2 — MX1" },
      { dia: "Domingo", hora: "18:30", sessao: "Pódio e Gala de encerramento" },
    ],
    distanciaVolta: "1,95 km",
    numeroVoltas: 16,
    recordeVolta: { piloto: "Nelson Kiala", tempo: "1:58.220", ano: 2025 },
    bilhetes: [
      {
        id: "geral",
        nome: "Geral",
        descricao: "Acesso livre às zonas de público em redor do circuito, nos dois dias.",
        preco: 3500,
        disponiveis: 2100,
        beneficios: ["Acesso 2 dias", "Zona de restauração", "Parque de estacionamento"],
      },
      {
        id: "bancada",
        nome: "Bancada Central",
        descricao: "Lugar numerado na nova bancada, de frente para a linha de partida e o tabletop.",
        preco: 9000,
        disponiveis: 480,
        beneficios: [
          "Acesso 2 dias",
          "Lugar numerado",
          "Vista sobre partida e tabletop",
          "Programa oficial",
        ],
        destaque: true,
      },
      {
        id: "vip",
        nome: "VIP Paddock Club",
        descricao: "A experiência completa: bancada, paddock, hospitalidade e pódio.",
        preco: 35000,
        disponiveis: 40,
        beneficios: [
          "Tudo da Bancada Central",
          "Acesso ao paddock",
          "Hospitalidade com catering",
          "Acesso à cerimónia do pódio",
          "Kit oficial + t-shirt",
          "Foto com os campeões",
        ],
      },
      {
        id: "familia",
        nome: "Bilhete Família",
        descricao: "2 adultos + 2 crianças até aos 12 anos, na zona geral.",
        preco: 10000,
        disponiveis: 300,
        beneficios: ["Acesso 2 dias para 4 pessoas", "Zona infantil", "Oferta de 4 bonés"],
      },
    ],
  },
  {
    slug: "gala-motobox-2026",
    titulo: "Gala Motobox — Prémios da Temporada",
    disciplina: "Passeio",
    temporada: 2026,
    circuito: "Talatona Convention Centre",
    provincia: "Luanda",
    localidade: "Talatona",
    dataInicio: "2026-12-12T19:00:00+01:00",
    dataFim: "2026-12-12T23:30:00+01:00",
    estado: "agendado",
    imagem: "gala",
    resumo:
      "A noite que fecha a temporada: entrega dos prémios nacionais e homenagem à comunidade motard angolana.",
    descricao:
      "Primeira edição da Gala Motobox. Entrega dos troféus de campeão nacional MX1, MX2 e Júnior, prémio de Revelação do Ano, prémio Clube do Ano e homenagem aos pilotos que se despedem da competição.",
    organizador: "Motobox Angola",
    horarios: [
      { dia: "Sábado", hora: "19:00", sessao: "Recepção e cocktail" },
      { dia: "Sábado", hora: "20:30", sessao: "Jantar" },
      { dia: "Sábado", hora: "21:30", sessao: "Cerimónia de entrega de prémios" },
      { dia: "Sábado", hora: "23:00", sessao: "Música e convívio" },
    ],
    bilhetes: [
      {
        id: "individual",
        nome: "Convite Individual",
        descricao: "Um lugar à mesa, com jantar incluído.",
        preco: 25000,
        disponiveis: 180,
        beneficios: ["Cocktail de recepção", "Jantar", "Cerimónia"],
        destaque: true,
      },
      {
        id: "mesa",
        nome: "Mesa Corporativa (8 lugares)",
        descricao: "Mesa reservada para empresas e patrocinadores, com identificação.",
        preco: 180000,
        disponiveis: 22,
        beneficios: [
          "8 lugares",
          "Mesa identificada",
          "Menção no programa",
          "Garrafa de espumante",
        ],
      },
    ],
  },
  {
    slug: "passeio-natal-luanda",
    titulo: "Passeio de Natal — Luanda",
    disciplina: "Solidária",
    temporada: 2026,
    circuito: "Marginal de Luanda — Cacuaco",
    provincia: "Luanda",
    localidade: "Luanda",
    dataInicio: "2026-12-20T08:00:00+01:00",
    dataFim: "2026-12-20T15:00:00+01:00",
    estado: "agendado",
    imagem: "natal",
    resumo:
      "O tradicional passeio de Natal, com entrega de brinquedos ao orfanato do Cacuaco. Aberto a toda a comunidade.",
    descricao:
      "Concentração na Marginal de Luanda e percurso até ao Cacuaco. A inscrição faz-se com a entrega de um brinquedo novo. No ano passado juntámos 340 motas e mais de 500 brinquedos.",
    organizador: "Motobox Angola",
    horarios: [
      { dia: "Domingo", hora: "08:00", sessao: "Concentração na Marginal" },
      { dia: "Domingo", hora: "09:30", sessao: "Partida" },
      { dia: "Domingo", hora: "11:00", sessao: "Chegada e entrega de brinquedos" },
      { dia: "Domingo", hora: "13:00", sessao: "Convívio" },
    ],
  },
];

/* ============================================================
   PILOTOS
   ============================================================ */

export const pilotos: Piloto[] = [
  {
    slug: "nelson-kiala",
    nome: "Nelson Kiala",
    apelido: "O Relâmpago do Kilamba",
    numero: 7,
    equipa: "Kilamba Racing",
    equipaSlug: "kilamba-racing",
    provincia: "Luanda",
    nacionalidade: "Angola",
    idade: 27,
    mota: "KTM 450 SX-F",
    categoria: "MX1",
    foto: "kiala",
    bio: "Bicampeão nacional e detentor do recorde de volta em três dos cinco circuitos do calendário. Começou aos 11 anos numa pocket bike emprestada no bairro do Kilamba e nunca mais parou. É hoje o rosto mais reconhecível do motocross angolano e o único piloto nacional a ter competido no campeonato sul-africano.",
    estreia: 2016,
    estatisticas: {
      pontos: 218,
      vitorias: 24,
      podios: 41,
      poles: 19,
      corridas: 68,
      melhorResultado: "1.º",
    },
    redes: { instagram: "https://instagram.com/nelsonkiala7", facebook: "#" },
    campeonatos: 2,
  },
  {
    slug: "bruno-tchipa",
    nome: "Bruno Tchipa",
    apelido: "O Homem da Tundavala",
    numero: 12,
    equipa: "Tundavala MX",
    equipaSlug: "tundavala-mx",
    provincia: "Huíla",
    nacionalidade: "Angola",
    idade: 30,
    mota: "Honda CRF 450R",
    categoria: "MX1",
    foto: "tchipa",
    bio: "Imbatível em casa. Cresceu a treinar nas encostas da Tundavala e traduz essa vantagem em resultados: nunca perdeu uma corrida no Lubango desde 2022. Mecânico de profissão, prepara a própria mota e é conhecido por partilhar afinações com os pilotos mais novos do paddock.",
    estreia: 2014,
    estatisticas: {
      pontos: 205,
      vitorias: 19,
      podios: 38,
      poles: 11,
      corridas: 79,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#", facebook: "#" },
    campeonatos: 1,
  },
  {
    slug: "adilson-mbala",
    nome: "Adilson Mbala",
    numero: 23,
    equipa: "Lobito Motorsport",
    equipaSlug: "lobito-motorsport",
    provincia: "Benguela",
    nacionalidade: "Angola",
    idade: 24,
    mota: "Yamaha YZ 450F",
    categoria: "MX1",
    foto: "mbala",
    bio: "Especialista em areia — o terreno do Lobito onde treina desde miúdo. Terceiro classificado nas duas últimas temporadas e o piloto com mais melhores voltas em 2026. Falta-lhe apenas converter velocidade em consistência.",
    estreia: 2019,
    estatisticas: {
      pontos: 191,
      vitorias: 9,
      podios: 27,
      poles: 14,
      corridas: 52,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#" },
    campeonatos: 0,
  },
  {
    slug: "eduardo-neto",
    nome: "Eduardo Neto",
    numero: 5,
    equipa: "Kilamba Racing",
    equipaSlug: "kilamba-racing",
    provincia: "Luanda",
    nacionalidade: "Angola",
    idade: 29,
    mota: "KTM 450 SX-F",
    categoria: "MX1",
    foto: "neto",
    bio: "O veterano do pelotão da frente. Dez temporadas no campeonato nacional e uma reputação de piloto limpo, que raramente comete erros. Colega de equipa de Nelson Kiala e peça-chave no desenvolvimento das afinações da Kilamba Racing.",
    estreia: 2015,
    estatisticas: {
      pontos: 168,
      vitorias: 6,
      podios: 24,
      poles: 5,
      corridas: 84,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#", facebook: "#" },
    campeonatos: 0,
  },
  {
    slug: "carlos-samba",
    nome: "Carlos Samba",
    numero: 44,
    equipa: "Namibe Dunas Team",
    equipaSlug: "namibe-dunas-team",
    provincia: "Namibe",
    nacionalidade: "Angola",
    idade: 33,
    mota: "Husqvarna FE 501",
    categoria: "Rally / Enduro",
    foto: "samba",
    bio: "Rei das dunas. Venceu quatro das últimas cinco edições da Corrida das Dunas do Namibe e é o único piloto angolano a ter terminado o Rali de Marrocos. Navegador exímio, prefere o roadbook às fitas do motocross.",
    estreia: 2012,
    estatisticas: {
      pontos: 154,
      vitorias: 14,
      podios: 22,
      poles: 8,
      corridas: 46,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#" },
    campeonatos: 1,
  },
  {
    slug: "ivandro-cabral",
    nome: "Ivandro Cabral",
    numero: 91,
    equipa: "Caála Racing Club",
    equipaSlug: "caala-racing-club",
    provincia: "Huambo",
    nacionalidade: "Angola",
    idade: 21,
    mota: "KTM 250 SX-F",
    categoria: "MX2",
    foto: "cabral",
    bio: "A grande revelação de 2026. Subiu de Júnior para MX2 e venceu à terceira corrida. Estilo agressivo, especialmente forte nas primeiras voltas. Toda a gente no paddock diz que é o próximo campeão nacional.",
    estreia: 2023,
    estatisticas: {
      pontos: 148,
      vitorias: 7,
      podios: 15,
      poles: 6,
      corridas: 24,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#", facebook: "#" },
    campeonatos: 0,
  },
  {
    slug: "helder-quissanga",
    nome: "Hélder Quissanga",
    numero: 18,
    equipa: "Cabinda Bikers",
    equipaSlug: "cabinda-bikers",
    provincia: "Cabinda",
    nacionalidade: "Angola",
    idade: 26,
    mota: "Honda CRF 250R",
    categoria: "MX2",
    foto: "quissanga",
    bio: "Percorre 600 km em cada fim de semana de prova para competir. Piloto de Cabinda, é o rosto do motocross no norte do país e o principal impulsionador da escola de jovens pilotos da província.",
    estreia: 2018,
    estatisticas: {
      pontos: 132,
      vitorias: 4,
      podios: 18,
      poles: 3,
      corridas: 58,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#" },
    campeonatos: 0,
  },
  {
    slug: "joana-ferraz",
    nome: "Joana Ferraz",
    apelido: "A Primeira",
    numero: 66,
    equipa: "Lobito Motorsport",
    equipaSlug: "lobito-motorsport",
    provincia: "Benguela",
    nacionalidade: "Angola",
    idade: 23,
    mota: "Yamaha YZ 250F",
    categoria: "MX2",
    foto: "ferraz",
    bio: "A primeira mulher a pontuar no Campeonato Nacional de Motocross e a primeira a subir ao pódio, no Lobito em 2025. Fundou o programa Elas de Capacete, que já colocou 30 raparigas em cima de uma mota. É, hoje, a piloto mais fotografada do paddock angolano.",
    estreia: 2021,
    estatisticas: {
      pontos: 118,
      vitorias: 2,
      podios: 9,
      poles: 2,
      corridas: 38,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#", facebook: "#" },
    campeonatos: 0,
  },
  {
    slug: "mario-bengui",
    nome: "Mário Bengui",
    numero: 34,
    equipa: "Tundavala MX",
    equipaSlug: "tundavala-mx",
    provincia: "Huíla",
    nacionalidade: "Angola",
    idade: 28,
    mota: "Honda CRF 450R",
    categoria: "MX1",
    foto: "bengui",
    bio: "Regressou à competição em 2025 depois de dois anos parado por lesão. Consistentemente entre os cinco primeiros, é o piloto que mais posições ganha na primeira volta de cada manga.",
    estreia: 2017,
    estatisticas: {
      pontos: 109,
      vitorias: 3,
      podios: 14,
      poles: 2,
      corridas: 61,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#" },
    campeonatos: 0,
  },
  {
    slug: "silvio-domingos",
    nome: "Sílvio Domingos",
    numero: 77,
    equipa: "Caála Racing Club",
    equipaSlug: "caala-racing-club",
    provincia: "Huambo",
    nacionalidade: "Angola",
    idade: 19,
    mota: "KTM 250 SX-F",
    categoria: "MX2",
    foto: "domingos",
    bio: "O mais novo do pelotão MX2. Saiu da categoria Júnior no ano passado com o título no bolso e adapta-se depressa. Treina no circuito da Caála todos os dias antes da escola.",
    estreia: 2025,
    estatisticas: {
      pontos: 94,
      vitorias: 1,
      podios: 6,
      poles: 1,
      corridas: 16,
      melhorResultado: "1.º",
    },
    redes: { instagram: "#" },
    campeonatos: 0,
  },
  {
    slug: "paulo-tembo",
    nome: "Paulo Tembo",
    numero: 29,
    equipa: "Namibe Dunas Team",
    equipaSlug: "namibe-dunas-team",
    provincia: "Namibe",
    nacionalidade: "Angola",
    idade: 31,
    mota: "Husqvarna FE 450",
    categoria: "Rally / Enduro",
    foto: "tembo",
    bio: "Parceiro de treino de Carlos Samba e segundo classificado nas duas últimas Corridas das Dunas. Mecânico de camiões em Moçâmedes, prepara a mota na oficina onde trabalha.",
    estreia: 2016,
    estatisticas: {
      pontos: 87,
      vitorias: 2,
      podios: 11,
      poles: 1,
      corridas: 41,
      melhorResultado: "1.º",
    },
    redes: {},
    campeonatos: 0,
  },
  {
    slug: "rui-katchimba",
    nome: "Rui Katchimba",
    numero: 8,
    equipa: "Cabinda Bikers",
    equipaSlug: "cabinda-bikers",
    provincia: "Cabinda",
    nacionalidade: "Angola",
    idade: 25,
    mota: "Kawasaki KX 250",
    categoria: "MX2",
    foto: "katchimba",
    bio: "Piloto polivalente, corre motocross e enduro na mesma temporada. Tem o melhor registo de fiabilidade do pelotão: 34 corridas consecutivas sem uma única desistência.",
    estreia: 2019,
    estatisticas: {
      pontos: 76,
      vitorias: 0,
      podios: 7,
      poles: 0,
      corridas: 49,
      melhorResultado: "2.º",
    },
    redes: { instagram: "#" },
    campeonatos: 0,
  },
];

/* ============================================================
   EQUIPAS E CLUBES
   ============================================================ */

export const equipas: Equipa[] = [
  {
    slug: "kilamba-racing",
    nome: "Kilamba Racing",
    tipo: "Equipa",
    base: "Kilamba Kiaxi, Luanda",
    provincia: "Luanda",
    fundacao: 2015,
    logo: "KR",
    cor: "#e10600",
    chefe: "Domingos Kiala",
    membros: 24,
    pilotos: ["nelson-kiala", "eduardo-neto"],
    descricao:
      "A equipa mais titulada do motocross angolano. Nasceu como uma oficina de bairro no Kilamba e cresceu até ser a estrutura de referência do país, com programa de formação de jovens pilotos e a única equipa nacional com camião de assistência próprio.",
    motas: ["KTM 450 SX-F", "KTM 250 SX-F"],
    estatisticas: { pontos: 386, vitorias: 30, podios: 65, titulos: 3 },
    redes: { instagram: "#", facebook: "#" },
  },
  {
    slug: "tundavala-mx",
    nome: "Tundavala MX",
    tipo: "Equipa",
    base: "Lubango, Huíla",
    provincia: "Huíla",
    fundacao: 2017,
    logo: "TX",
    cor: "#0ea5e9",
    chefe: "Alberto Tchipa",
    membros: 18,
    pilotos: ["bruno-tchipa", "mario-bengui"],
    descricao:
      "Equipa do planalto, treina a 1.700 metros de altitude e faz dessa dureza uma vantagem competitiva. Especialistas em preparação de motores para altitude — presta serviço a outras equipas do calendário.",
    motas: ["Honda CRF 450R"],
    estatisticas: { pontos: 314, vitorias: 22, podios: 52, titulos: 1 },
    redes: { instagram: "#", facebook: "#" },
  },
  {
    slug: "lobito-motorsport",
    nome: "Lobito Motorsport",
    tipo: "Equipa",
    base: "Lobito, Benguela",
    provincia: "Benguela",
    fundacao: 2019,
    logo: "LM",
    cor: "#f59e0b",
    chefe: "Sandra Ferraz",
    membros: 21,
    pilotos: ["adilson-mbala", "joana-ferraz"],
    descricao:
      "A equipa da restinga. Treina na areia do Lobito e domina as provas de terreno solto. É também a única equipa do campeonato dirigida por uma mulher e a casa do programa Elas de Capacete.",
    motas: ["Yamaha YZ 450F", "Yamaha YZ 250F"],
    estatisticas: { pontos: 309, vitorias: 11, podios: 36, titulos: 0 },
    redes: { instagram: "#", facebook: "#" },
  },
  {
    slug: "caala-racing-club",
    nome: "Caála Racing Club",
    tipo: "Clube",
    base: "Caála, Huambo",
    provincia: "Huambo",
    fundacao: 2021,
    logo: "CRC",
    cor: "#22c55e",
    chefe: "Nuno Chivela",
    membros: 46,
    pilotos: ["ivandro-cabral", "silvio-domingos"],
    descricao:
      "Clube jovem e a crescer depressa. Gere o circuito da Caála e tem a maior escola de pilotagem do interior do país, com 30 miúdos inscritos na categoria Júnior. A aposta na formação já está a dar frutos no pelotão MX2.",
    motas: ["KTM 250 SX-F"],
    estatisticas: { pontos: 242, vitorias: 8, podios: 21, titulos: 0 },
    redes: { instagram: "#", facebook: "#" },
  },
  {
    slug: "namibe-dunas-team",
    nome: "Namibe Dunas Team",
    tipo: "Equipa",
    base: "Moçâmedes, Namibe",
    provincia: "Namibe",
    fundacao: 2013,
    logo: "NDT",
    cor: "#a855f7",
    chefe: "Carlos Samba",
    membros: 12,
    pilotos: ["carlos-samba", "paulo-tembo"],
    descricao:
      "Equipa especializada em rally-raid e enduro no deserto. Pequena, mas com o melhor conhecimento de navegação e sobrevivência em dunas do país. Organiza estágios de preparação para pilotos estrangeiros que visitam o Namibe.",
    motas: ["Husqvarna FE 501", "Husqvarna FE 450"],
    estatisticas: { pontos: 241, vitorias: 16, podios: 33, titulos: 1 },
    redes: { instagram: "#" },
  },
  {
    slug: "cabinda-bikers",
    nome: "Cabinda Bikers",
    tipo: "Clube",
    base: "Cabinda",
    provincia: "Cabinda",
    fundacao: 2016,
    logo: "CB",
    cor: "#14b8a6",
    chefe: "Hélder Quissanga",
    membros: 58,
    pilotos: ["helder-quissanga", "rui-katchimba"],
    descricao:
      "O maior clube motard do norte do país. Mais do que uma equipa de competição, é uma comunidade: organiza passeios mensais, acções solidárias e a maior concentração motard de Cabinda, que junta clubes dos dois Congos.",
    motas: ["Honda CRF 250R", "Kawasaki KX 250"],
    estatisticas: { pontos: 208, vitorias: 4, podios: 25, titulos: 0 },
    redes: { instagram: "#", facebook: "#" },
  },
  {
    slug: "moto-clube-luanda",
    nome: "Moto Clube de Luanda",
    tipo: "Clube",
    base: "Ingombota, Luanda",
    provincia: "Luanda",
    fundacao: 2008,
    logo: "MCL",
    cor: "#64748b",
    chefe: "Fernando Bastos",
    membros: 134,
    pilotos: [],
    descricao:
      "O clube mais antigo em actividade em Angola e o maior em número de membros. Não compete: dedica-se a passeios, ao convívio e a acções sociais. Organiza o Passeio de Natal em parceria com a Motobox desde 2019.",
    motas: ["Estrada", "Trail", "Custom"],
    estatisticas: { pontos: 0, vitorias: 0, podios: 0, titulos: 0 },
    redes: { instagram: "#", facebook: "#" },
  },
  {
    slug: "trail-angola",
    nome: "Trail Angola",
    tipo: "Clube",
    base: "Talatona, Luanda",
    provincia: "Luanda",
    fundacao: 2020,
    logo: "TA",
    cor: "#e11d48",
    chefe: "Miguel Sousa",
    membros: 72,
    pilotos: [],
    descricao:
      "Clube dedicado ao trail e às viagens de longo curso. Já organizou travessias Luanda–Namibe e Luanda–Cabinda, e mantém um roteiro público de trilhos por província que qualquer motard pode consultar.",
    motas: ["Trail", "Adventure"],
    estatisticas: { pontos: 0, vitorias: 0, podios: 0, titulos: 0 },
    redes: { instagram: "#", facebook: "#" },
  },
];

/* ============================================================
   RESULTADOS / CORRIDAS
   ============================================================ */

export const corridas: Corrida[] = [
  {
    slug: "gp-luanda-2026-mx1",
    eventoSlug: "gp-luanda-abertura",
    nome: "GP de Luanda",
    ronda: 1,
    temporada: 2026,
    circuito: "Circuito do Kilamba",
    provincia: "Luanda",
    data: "2026-03-15",
    categoria: "MX1",
    vencedor: "Nelson Kiala",
    imagem: "kilamba",
    resultados: [
      { posicao: 1, pilotoSlug: "nelson-kiala", piloto: "Nelson Kiala", equipa: "Kilamba Racing", voltas: 16, tempo: "31:24.118", pontos: 25, melhorVolta: true },
      { posicao: 2, pilotoSlug: "bruno-tchipa", piloto: "Bruno Tchipa", equipa: "Tundavala MX", voltas: 16, tempo: "+4.882", pontos: 22 },
      { posicao: 3, pilotoSlug: "adilson-mbala", piloto: "Adilson Mbala", equipa: "Lobito Motorsport", voltas: 16, tempo: "+11.204", pontos: 20 },
      { posicao: 4, pilotoSlug: "eduardo-neto", piloto: "Eduardo Neto", equipa: "Kilamba Racing", voltas: 16, tempo: "+19.771", pontos: 18 },
      { posicao: 5, pilotoSlug: "mario-bengui", piloto: "Mário Bengui", equipa: "Tundavala MX", voltas: 16, tempo: "+28.340", pontos: 16 },
      { posicao: 6, pilotoSlug: "rui-katchimba", piloto: "Rui Katchimba", equipa: "Cabinda Bikers", voltas: 15, tempo: "+1 volta", pontos: 15 },
    ],
  },
  {
    slug: "gp-luanda-2026-mx2",
    eventoSlug: "gp-luanda-abertura",
    nome: "GP de Luanda",
    ronda: 1,
    temporada: 2026,
    circuito: "Circuito do Kilamba",
    provincia: "Luanda",
    data: "2026-03-15",
    categoria: "MX2",
    vencedor: "Ivandro Cabral",
    imagem: "kilamba",
    resultados: [
      { posicao: 1, pilotoSlug: "ivandro-cabral", piloto: "Ivandro Cabral", equipa: "Caála Racing Club", voltas: 14, tempo: "29:02.551", pontos: 25 },
      { posicao: 2, pilotoSlug: "helder-quissanga", piloto: "Hélder Quissanga", equipa: "Cabinda Bikers", voltas: 14, tempo: "+6.119", pontos: 22, melhorVolta: true },
      { posicao: 3, pilotoSlug: "silvio-domingos", piloto: "Sílvio Domingos", equipa: "Caála Racing Club", voltas: 14, tempo: "+14.660", pontos: 20 },
      { posicao: 4, pilotoSlug: "joana-ferraz", piloto: "Joana Ferraz", equipa: "Lobito Motorsport", voltas: 14, tempo: "+22.017", pontos: 18 },
      { posicao: 5, pilotoSlug: "rui-katchimba", piloto: "Rui Katchimba", equipa: "Cabinda Bikers", voltas: 14, tempo: "+35.284", pontos: 16 },
    ],
  },
  {
    slug: "enduro-benguela-2026",
    eventoSlug: "enduro-benguela",
    nome: "Enduro do Litoral",
    ronda: 2,
    temporada: 2026,
    circuito: "Percurso da Restinga",
    provincia: "Benguela",
    data: "2026-04-19",
    categoria: "Enduro",
    vencedor: "Adilson Mbala",
    imagem: "benguela",
    resultados: [
      { posicao: 1, pilotoSlug: "adilson-mbala", piloto: "Adilson Mbala", equipa: "Lobito Motorsport", voltas: 6, tempo: "4:12:08", pontos: 25, melhorVolta: true },
      { posicao: 2, pilotoSlug: "carlos-samba", piloto: "Carlos Samba", equipa: "Namibe Dunas Team", voltas: 6, tempo: "+2:44", pontos: 22 },
      { posicao: 3, pilotoSlug: "nelson-kiala", piloto: "Nelson Kiala", equipa: "Kilamba Racing", voltas: 6, tempo: "+5:19", pontos: 20 },
      { posicao: 4, pilotoSlug: "paulo-tembo", piloto: "Paulo Tembo", equipa: "Namibe Dunas Team", voltas: 6, tempo: "+8:02", pontos: 18 },
      { posicao: 5, pilotoSlug: "rui-katchimba", piloto: "Rui Katchimba", equipa: "Cabinda Bikers", voltas: 6, tempo: "+13:37", pontos: 16 },
      { posicao: 0, pilotoSlug: "bruno-tchipa", piloto: "Bruno Tchipa", equipa: "Tundavala MX", voltas: 3, tempo: "—", pontos: 0, estado: "DNF" },
    ],
  },
  {
    slug: "gp-huila-2026-mx1",
    eventoSlug: "gp-huila-lubango",
    nome: "GP da Huíla",
    ronda: 3,
    temporada: 2026,
    circuito: "Circuito da Tundavala",
    provincia: "Huíla",
    data: "2026-06-14",
    categoria: "MX1",
    vencedor: "Bruno Tchipa",
    imagem: "lubango",
    resultados: [
      { posicao: 1, pilotoSlug: "bruno-tchipa", piloto: "Bruno Tchipa", equipa: "Tundavala MX", voltas: 14, tempo: "30:11.402", pontos: 25, melhorVolta: true },
      { posicao: 2, pilotoSlug: "nelson-kiala", piloto: "Nelson Kiala", equipa: "Kilamba Racing", voltas: 14, tempo: "+3.117", pontos: 22 },
      { posicao: 3, pilotoSlug: "mario-bengui", piloto: "Mário Bengui", equipa: "Tundavala MX", voltas: 14, tempo: "+16.885", pontos: 20 },
      { posicao: 4, pilotoSlug: "eduardo-neto", piloto: "Eduardo Neto", equipa: "Kilamba Racing", voltas: 14, tempo: "+24.209", pontos: 18 },
      { posicao: 5, pilotoSlug: "adilson-mbala", piloto: "Adilson Mbala", equipa: "Lobito Motorsport", voltas: 14, tempo: "+31.556", pontos: 16 },
    ],
  },
  {
    slug: "gp-huila-2026-mx2",
    eventoSlug: "gp-huila-lubango",
    nome: "GP da Huíla",
    ronda: 3,
    temporada: 2026,
    circuito: "Circuito da Tundavala",
    provincia: "Huíla",
    data: "2026-06-14",
    categoria: "MX2",
    vencedor: "Ivandro Cabral",
    imagem: "lubango",
    resultados: [
      { posicao: 1, pilotoSlug: "ivandro-cabral", piloto: "Ivandro Cabral", equipa: "Caála Racing Club", voltas: 12, tempo: "27:48.930", pontos: 25, melhorVolta: true },
      { posicao: 2, pilotoSlug: "joana-ferraz", piloto: "Joana Ferraz", equipa: "Lobito Motorsport", voltas: 12, tempo: "+9.402", pontos: 22 },
      { posicao: 3, pilotoSlug: "silvio-domingos", piloto: "Sílvio Domingos", equipa: "Caála Racing Club", voltas: 12, tempo: "+15.118", pontos: 20 },
      { posicao: 4, pilotoSlug: "helder-quissanga", piloto: "Hélder Quissanga", equipa: "Cabinda Bikers", voltas: 12, tempo: "+20.774", pontos: 18 },
    ],
  },
];

/* ============================================================
   NOTÍCIAS
   ============================================================ */

export const noticias: Noticia[] = [
  {
    slug: "campeonato-decide-se-no-huambo",
    titulo: "Campeonato decide-se no Huambo com apenas 13 pontos entre os três primeiros",
    resumo:
      "Nelson Kiala chega à final com 218 pontos, seguido de Bruno Tchipa (205) e Adilson Mbala (191). Com pontuação a dobrar na Caála, qualquer um dos três pode ser campeão.",
    corpo: [
      "A temporada 2026 do Campeonato Nacional de Motocross entra na última ronda com o desfecho mais apertado dos últimos dez anos. Nelson Kiala lidera com 218 pontos, mas a vantagem de 13 sobre Bruno Tchipa não chega para garantir o tricampeonato — e com a pontuação a dobrar na final da Caála, Adilson Mbala, 27 pontos atrás, também continua matematicamente na corrida.",
      "\"Não penso na tabela. Penso em ganhar as duas mangas e acabou\", disse Kiala à Motobox no final dos treinos de preparação no Kilamba. O piloto da Kilamba Racing venceu duas das quatro rondas disputadas, mas cedeu terreno no Lubango, onde Tchipa é praticamente imbatível.",
      "Bruno Tchipa, por seu lado, chega à Caála com o argumento da forma: venceu a última ronda e assinou a melhor volta em três das quatro provas do ano. \"Toda a gente sabe que o Nelson é rápido. Mas na Caála é terreno duro, e terreno duro é onde eu me sinto em casa.\"",
      "Adilson Mbala precisa de um cenário improvável — vencer as duas mangas e contar com problemas dos dois rivais — mas o piloto do Lobito não desarma: \"Já vi campeonatos decidirem-se por menos. A minha função é ganhar. O resto não controlo.\"",
      "A ronda final disputa-se a 21 e 22 de Novembro no Circuito da Caála, com a nova bancada para 3.000 espectadores a estrear-se nesta prova. Os bilhetes estão à venda na Motobox.",
    ],
    categoria: "Angola",
    tags: ["MX1", "Campeonato", "Huambo", "Nelson Kiala", "Bruno Tchipa"],
    autor: "Redacção Motobox",
    data: "2026-11-08",
    imagem: "huambo",
    leitura: 4,
    destaque: true,
  },
  {
    slug: "joana-ferraz-entrevista",
    titulo: "Joana Ferraz: \"Quando cheguei, diziam-me que aquilo não era lugar para mim\"",
    resumo:
      "A primeira mulher a pontuar e a subir ao pódio no campeonato nacional fala sobre o programa Elas de Capacete, as 30 raparigas que já colocou em cima de uma mota, e o que ainda falta mudar no paddock angolano.",
    corpo: [
      "Encontrámos Joana Ferraz na oficina da Lobito Motorsport, com as mãos sujas de massa lubrificante e a corrente da YZ 250F desmontada em cima da bancada. Faz a manutenção da própria mota desde os 17 anos. \"Se não souber o que a mota tem, não sei o que lhe pedir na pista.\"",
      "Chegou ao paddock em 2021, aos 18 anos. \"Na primeira corrida houve quem se risse. Um senhor disse ao meu pai que aquilo não era lugar para mim. Acabei em nono. No ano seguinte fui sétima. Em 2025 subi ao pódio no Lobito e esse mesmo senhor veio dar-me os parabéns.\"",
      "O programa Elas de Capacete nasceu dessa experiência. Começou com três raparigas e uma mota emprestada, aos sábados de manhã na restinga. Hoje são 30, com quatro motas do clube e uma lista de espera. \"Não é sobre fazer campeãs. É sobre não deixar que nenhuma pense que aquilo não é lugar para ela.\"",
      "Sobre o resto — os balneários, os patrocínios, a cobertura — Joana é directa: \"Mudou muito. Mas ainda há provas onde me troco atrás da carrinha. Não me queixo, digo só que se resolve com pouco dinheiro e ninguém resolveu ainda.\"",
      "Este ano é quarta classificada em MX2 e chega à final da Caála com hipóteses reais de terminar no pódio do campeonato. Seria outra primeira vez.",
    ],
    categoria: "Entrevista",
    tags: ["Joana Ferraz", "MX2", "Elas de Capacete", "Lobito"],
    autor: "Sofia Mussungo",
    data: "2026-10-24",
    imagem: "ferraz",
    leitura: 6,
    destaque: true,
  },
  {
    slug: "corrida-dunas-namibe-preview",
    titulo: "Corrida das Dunas: 240 km de deserto e um roadbook que ninguém viu",
    resumo:
      "A prova mais espectacular do calendário regressa ao Namibe a 10 e 11 de Outubro. Carlos Samba defende quatro vitórias em cinco edições.",
    corpo: [
      "A organização manteve o percurso em segredo até 24 horas antes da partida, como manda a tradição do rally-raid. Sabe-se apenas que são 240 km divididos em duas etapas e que a organização acrescentou uma secção nova na zona norte das dunas.",
      "Carlos Samba, quatro vezes vencedor, admite que a novidade lhe tira alguma vantagem: \"Conheço as dunas todas. Mas conhecer não chega quando o roadbook manda-te por onde nunca foste. É isso que torna a prova bonita.\"",
      "A prova tem este ano transmissão das câmaras de bordo para o ecrã gigante montado no acampamento de partida, uma estreia no motociclismo angolano. Os bilhetes de Tribuna Coberta e Paddock Pass já estão à venda.",
    ],
    categoria: "Angola",
    tags: ["Rally", "Namibe", "Carlos Samba", "Dunas"],
    autor: "Gonçalo Pinto",
    data: "2026-10-02",
    imagem: "namibe",
    leitura: 3,
  },
  {
    slug: "passeio-cabinda-material-escolar",
    titulo: "120 motas, 90 km e três escolas: o Passeio Solidário de Cabinda em números",
    resumo:
      "A edição de 2026 juntou clubes de cinco províncias e entregou material escolar a 340 alunos do município de Buco-Zau.",
    corpo: [
      "Partiram de Cabinda às nove da manhã e chegaram a Buco-Zau ao meio-dia. No meio, 90 quilómetros de estrada e picada, e nas malas de cada mota o que ali fazia a inscrição na prova: cadernos, lápis, mochilas.",
      "\"Isto começou com doze motas em 2019\", contou Hélder Quissanga, do Cabinda Bikers, que co-organiza a iniciativa com a Motobox. \"Este ano contámos 124 na partida. Vieram clubes de Luanda, do Uíge, até do Lobito.\"",
      "O material foi distribuído por três escolas do município, abrangendo 340 alunos. A Motobox agradece a todos os clubes participantes e aos patrocinadores que garantiram o combustível e o almoço.",
    ],
    categoria: "Solidária",
    tags: ["Cabinda", "Solidariedade", "Passeio", "Comunidade"],
    autor: "Redacção Motobox",
    data: "2026-08-12",
    imagem: "cabinda",
    leitura: 3,
  },
  {
    slug: "ivandro-cabral-revelacao",
    titulo: "Ivandro Cabral, 21 anos: da escola da Caála à liderança do MX2",
    resumo:
      "Subiu de Júnior esta temporada e venceu à terceira corrida. O clube que o formou já prepara o próximo.",
    corpo: [
      "A escola de pilotagem do Caála Racing Club tem 30 miúdos inscritos e uma sala com quatro motas partilhadas. Ivandro Cabral saiu de lá há três anos. Este ano lidera o MX2 e é o nome que toda a gente aponta como próximo campeão nacional.",
      "\"O clube deu-me tudo. A mota, o transporte para as provas, o mecânico. Se não fosse o Caála eu estava a trabalhar e não a correr\", disse depois da vitória no Lubango.",
      "Nuno Chivela, presidente do clube, tem outra leitura: \"O Ivandro é o que se vê. O que não se vê são os outros 29 que estão lá aos sábados. Não vamos fazer 29 campeões, mas vamos fazer 29 pessoas com uma coisa boa para fazer ao fim-de-semana.\"",
    ],
    categoria: "Angola",
    tags: ["MX2", "Ivandro Cabral", "Huambo", "Formação"],
    autor: "Redacção Motobox",
    data: "2026-06-20",
    imagem: "cabral",
    leitura: 4,
  },
  {
    slug: "mxgp-calendario-2027",
    titulo: "MXGP anuncia calendário de 2027 com 21 rondas e estreia em África",
    resumo:
      "O Mundial de Motocross regressa ao continente africano pela primeira vez desde 2017, com uma ronda marcada para a África do Sul.",
    corpo: [
      "A Infront Moto Racing divulgou o calendário provisório do MXGP 2027, com 21 grandes prémios e o regresso de África ao mapa do mundial. A prova sul-africana está agendada para Setembro.",
      "Para os pilotos angolanos, a proximidade é uma oportunidade: é o grande prémio de motocross de topo mais perto de casa em uma década. Nelson Kiala, o único angolano com experiência de competição na África do Sul, já manifestou intenção de estar presente.",
    ],
    categoria: "Internacional",
    tags: ["MXGP", "Mundial", "Calendário", "África do Sul"],
    autor: "Agregação automática",
    data: "2026-11-02",
    imagem: "mxgp",
    leitura: 2,
    fonte: "MXGP.com",
    fonteUrl: "https://www.mxgp.com",
  },
  {
    slug: "ktm-nova-450-2027",
    titulo: "KTM apresenta a nova 450 SX-F para 2027 com chassis redesenhado",
    resumo:
      "A marca austríaca revelou a geração 2027 da sua moto de motocross de topo, com menos 1,2 kg e nova geometria de suspensão.",
    corpo: [
      "A KTM revelou a 450 SX-F de 2027, com um chassis de aço-crómio-molibdénio redesenhado que reduz o peso em 1,2 kg e altera a rigidez lateral em 4%. A suspensão WP XACT recebe uma nova cartucheira e o motor ganha 1,5 cv.",
      "É a mota utilizada pela Kilamba Racing no campeonato nacional. A chegada de unidades a Angola está prevista para o segundo trimestre de 2027, através do importador oficial.",
    ],
    categoria: "Internacional",
    tags: ["KTM", "Material", "MX1", "2027"],
    autor: "Agregação automática",
    data: "2026-10-28",
    imagem: "ktm",
    leitura: 2,
    fonte: "Motocross Action",
    fonteUrl: "#",
  },
  {
    slug: "dakar-2027-inscricoes",
    titulo: "Dakar 2027: inscrições abertas na categoria Rally 2 para privados",
    resumo:
      "A ASO abriu as inscrições para a edição de 2027 do Dakar. A categoria Rally 2 continua a ser a porta de entrada para pilotos privados.",
    corpo: [
      "A Amaury Sport Organisation abriu o período de inscrições para o Dakar 2027, que se disputa novamente na Arábia Saudita em Janeiro. A categoria Rally 2, criada para pilotos privados com material de série, mantém-se como a via mais acessível.",
      "Carlos Samba, do Namibe Dunas Team, é o único angolano a ter terminado uma prova do calendário mundial de rally-raid, no Rali de Marrocos. Questionado sobre o Dakar, respondeu apenas: \"Um dia. Quando houver dinheiro.\"",
    ],
    categoria: "Internacional",
    tags: ["Dakar", "Rally", "Carlos Samba"],
    autor: "Agregação automática",
    data: "2026-10-15",
    imagem: "dakar",
    leitura: 2,
    fonte: "Dakar.com",
    fonteUrl: "https://www.dakar.com",
  },
  {
    slug: "concentracao-motard-lubango",
    titulo: "Concentração motard do Lubango junta 400 motas no planalto",
    resumo:
      "A maior concentração do interior do país celebrou a sexta edição com clubes vindos de sete províncias e da Namíbia.",
    corpo: [
      "O parque da Tundavala encheu-se de motas no primeiro fim-de-semana de Setembro. A sexta concentração motard do Lubango contou 412 motas registadas e clubes de sete províncias angolanas, além de dois clubes vindos da Namíbia.",
      "O programa incluiu passeio pela Serra da Leba, exposição de motas clássicas e um concerto no sábado à noite. A organização anunciou já a data de 2027.",
    ],
    categoria: "Comunidade",
    tags: ["Concentração", "Lubango", "Comunidade", "Passeio"],
    autor: "Gonçalo Pinto",
    data: "2026-09-08",
    imagem: "lubango",
    leitura: 3,
  },
];

/* ============================================================
   VÍDEOS
   ============================================================ */

export const videos: Video[] = [
  {
    slug: "highlights-gp-huila-2026",
    titulo: "HIGHLIGHTS — GP da Huíla 2026",
    descricao: "Os melhores momentos das duas mangas de MX1 no circuito da Tundavala, incluindo o duelo Tchipa–Kiala na volta 11.",
    duracao: "8:42",
    data: "2026-06-15",
    thumbnail: "lubango",
    categoria: "Highlights",
    visualizacoes: 24800,
    videoId: "ZDTwsTIrIPA",
    evento: "GP da Huíla",
  },
  {
    slug: "onboard-kiala-kilamba",
    titulo: "ONBOARD — Nelson Kiala, volta de qualificação no Kilamba",
    descricao: "Uma volta completa com Nelson Kiala em modo de qualificação. Câmara de bordo, som de motor, sem comentário.",
    duracao: "2:04",
    data: "2026-03-14",
    thumbnail: "kilamba",
    categoria: "Onboard",
    visualizacoes: 41200,
    videoId: "c87dWl93K1M",
    evento: "GP de Luanda",
  },
  {
    slug: "documentario-elas-de-capacete",
    titulo: "ELAS DE CAPACETE — O documentário",
    descricao: "Seis meses a acompanhar as 30 raparigas do programa fundado por Joana Ferraz na restinga do Lobito.",
    duracao: "24:15",
    data: "2026-09-30",
    thumbnail: "ferraz",
    categoria: "Documentário",
    visualizacoes: 68400,
    videoId: "nfMHEYkZIkw",
  },
  {
    slug: "resumo-enduro-litoral",
    titulo: "RESUMO — Enduro do Litoral, Benguela",
    descricao: "Dois dias, seis especiais, 84 km. O resumo da prova mais dura do calendário nacional.",
    duracao: "12:30",
    data: "2026-04-20",
    thumbnail: "benguela",
    categoria: "Resumo",
    visualizacoes: 18900,
    videoId: "8tLkPnTUw2g",
    evento: "Enduro do Litoral",
  },
  {
    slug: "entrevista-carlos-samba",
    titulo: "ENTREVISTA — Carlos Samba, o rei das dunas",
    descricao: "Conversa em Moçâmedes sobre navegação, deserto, e o que é preciso para chegar ao Dakar a partir de Angola.",
    duracao: "17:08",
    data: "2026-09-20",
    thumbnail: "namibe",
    categoria: "Entrevista",
    visualizacoes: 15300,
    videoId: "9kqeB10qIxw",
  },
  {
    slug: "passeio-cabinda-2026",
    titulo: "PASSEIO SOLIDÁRIO DE CABINDA 2026",
    descricao: "124 motas, 90 km e material escolar para 340 alunos. Como foi o dia, do princípio ao fim.",
    duracao: "9:55",
    data: "2026-08-14",
    thumbnail: "cabinda",
    categoria: "Resumo",
    visualizacoes: 32100,
    videoId: "a4Wgw0aS34k",
    evento: "Passeio Solidário de Cabinda",
  },
  {
    slug: "highlights-gp-luanda-2026",
    titulo: "HIGHLIGHTS — GP de Luanda 2026",
    descricao: "A abertura da temporada no Kilamba. Kiala vence, Cabral estreia-se a ganhar em MX2.",
    duracao: "10:21",
    data: "2026-03-16",
    thumbnail: "kilamba",
    categoria: "Highlights",
    visualizacoes: 29600,
    videoId: "c87dWl93K1M",
    evento: "GP de Luanda",
  },
  {
    slug: "top10-saltos-2026",
    titulo: "TOP 10 — Os melhores saltos da temporada",
    descricao: "Compilação dos dez saltos mais espectaculares do campeonato nacional de 2026.",
    duracao: "5:47",
    data: "2026-10-30",
    thumbnail: "huambo",
    categoria: "Highlights",
    visualizacoes: 52700,
    videoId: "ZDTwsTIrIPA",
  },
];

/* ============================================================
   PATROCINADORES
   ============================================================ */

export const patrocinadores: Patrocinador[] = [
  {
    slug: "banco-atlantico",
    nome: "Banco Atlântico",
    nivel: "Principal",
    setor: "Serviços financeiros",
    descricao:
      "Patrocinador principal do Campeonato Nacional de Motocross e parceiro da Motobox desde o primeiro dia. Financia o programa de formação de jovens pilotos.",
    logo: "BA",
    website: "#",
    desde: 2023,
  },
  {
    slug: "unitel",
    nome: "Unitel",
    nivel: "Principal",
    setor: "Telecomunicações",
    descricao:
      "Garante a conectividade nos circuitos e a transmissão em direto das provas do calendário nacional.",
    logo: "UN",
    website: "#",
    desde: 2024,
  },
  {
    slug: "sonangol",
    nome: "Sonangol",
    nivel: "Oficial",
    setor: "Energia",
    descricao: "Fornecedor oficial de combustíveis e lubrificantes do campeonato nacional.",
    logo: "SG",
    website: "#",
    desde: 2024,
  },
  {
    slug: "motocenter-luanda",
    nome: "MotoCenter Luanda",
    nivel: "Oficial",
    setor: "Concessionário e oficina",
    descricao:
      "O maior concessionário de motas de Angola. Assistência técnica oficial em todas as provas do calendário.",
    logo: "MC",
    website: "#",
    desde: 2022,
  },
  {
    slug: "ktm-angola",
    nome: "KTM Angola",
    nivel: "Oficial",
    setor: "Importador de motociclos",
    descricao: "Importador oficial KTM e Husqvarna em Angola. Fornecedor de material a três equipas do campeonato.",
    logo: "KTM",
    website: "#",
    desde: 2023,
  },
  {
    slug: "refriango",
    nome: "Refriango",
    nivel: "Apoio",
    setor: "Bebidas",
    descricao: "Apoia as zonas de restauração e hidratação de pilotos em todas as provas.",
    logo: "RF",
    website: "#",
    desde: 2025,
  },
  {
    slug: "clinica-girassol",
    nome: "Clínica Girassol",
    nivel: "Apoio",
    setor: "Saúde",
    descricao: "Assistência médica de emergência nos circuitos e apoio na recuperação de pilotos lesionados.",
    logo: "CG",
    website: "#",
    desde: 2024,
  },
  {
    slug: "capacetes-ao",
    nome: "Capacetes.ao",
    nivel: "Apoio",
    setor: "Equipamento de protecção",
    descricao: "Loja online de equipamento de protecção. Parceira do programa Elas de Capacete.",
    logo: "CA",
    website: "#",
    desde: 2025,
  },
  {
    slug: "tpa-desporto",
    nome: "TPA Desporto",
    nivel: "Media",
    setor: "Televisão",
    descricao: "Parceiro de media para a transmissão televisiva dos resumos das provas nacionais.",
    logo: "TPA",
    website: "#",
    desde: 2025,
  },
  {
    slug: "radio-lac",
    nome: "Rádio LAC",
    nivel: "Media",
    setor: "Rádio",
    descricao: "Cobertura radiofónica das provas e programa semanal dedicado ao motociclismo angolano.",
    logo: "LAC",
    website: "#",
    desde: 2026,
  },
];

/* ============================================================
   MARKETPLACE
   ============================================================ */

export const anuncios: AnuncioMarketplace[] = [
  {
    id: "mkt-001",
    titulo: "KTM 250 SX-F 2023 — pronta para competição",
    categoria: "Motas",
    preco: 6800000,
    negociavel: true,
    marca: "KTM",
    modelo: "250 SX-F",
    ano: 2023,
    quilometragem: 78,
    estado: "Muito bom",
    provincia: "Luanda",
    descricao:
      "Mota de competição usada apenas em duas temporadas do campeonato nacional. Motor revisto há 12 horas de utilização, suspensão WP com serviço feito, kit de transmissão novo. Acompanha suporte de box e jogo de plásticos suplente. Documentação em ordem.",
    imagens: ["ktm250"],
    vendedor: { nome: "Kilamba Racing", verificado: true, desde: 2023, anuncios: 7, avaliacao: 4.9 },
    publicado: "2026-11-02",
    visualizacoes: 1240,
  },
  {
    id: "mkt-002",
    titulo: "Capacete Fox V3 RS — tamanho M, como novo",
    categoria: "Equipamento",
    preco: 320000,
    negociavel: false,
    marca: "Fox Racing",
    modelo: "V3 RS",
    estado: "Como nova",
    provincia: "Luanda",
    descricao:
      "Capacete usado em três provas. Sem quedas. Certificação ECE 22.06 e MIPS. Vem com saco original e viseira suplente. Tamanho M (57-58 cm).",
    imagens: ["capacete"],
    vendedor: { nome: "André Fonseca", verificado: true, desde: 2024, anuncios: 3, avaliacao: 5 },
    publicado: "2026-11-05",
    visualizacoes: 486,
  },
  {
    id: "mkt-003",
    titulo: "Honda CRF 450R 2021 — trail e enduro",
    categoria: "Motas",
    preco: 5200000,
    negociavel: true,
    marca: "Honda",
    modelo: "CRF 450R",
    ano: 2021,
    quilometragem: 4200,
    estado: "Bom",
    provincia: "Benguela",
    descricao:
      "Usada em passeios e provas de enduro amador. Pneus novos, travões revistos, kit de iluminação instalado para uso em trilho. Alguns riscos nos plásticos, nada de estrutural. Aceito troca por mota de estrada.",
    imagens: ["crf450"],
    vendedor: { nome: "Rui Katchimba", verificado: true, desde: 2022, anuncios: 2, avaliacao: 4.8 },
    publicado: "2026-10-28",
    visualizacoes: 892,
  },
  {
    id: "mkt-004",
    titulo: "Jogo de suspensão WP XACT — revisto",
    categoria: "Peças",
    preco: 890000,
    negociavel: true,
    marca: "WP Suspension",
    modelo: "XACT 48",
    estado: "Muito bom",
    provincia: "Luanda",
    descricao:
      "Forquilha e amortecedor WP XACT retirados de KTM 450 SX-F 2022. Revisão completa feita na MotoCenter há 3 meses, com factura. Molas para piloto de 75-85 kg.",
    imagens: ["suspensao"],
    vendedor: { nome: "MotoCenter Luanda", verificado: true, desde: 2022, anuncios: 24, avaliacao: 4.7 },
    publicado: "2026-10-30",
    visualizacoes: 341,
  },
  {
    id: "mkt-005",
    titulo: "Yamaha Ténéré 700 2022 — pronta para viajar",
    categoria: "Motas",
    preco: 9400000,
    negociavel: false,
    marca: "Yamaha",
    modelo: "Ténéré 700",
    ano: 2022,
    quilometragem: 18500,
    estado: "Muito bom",
    provincia: "Luanda",
    descricao:
      "Trail preparada para viagem: malas laterais Givi, top case, protecção de motor, guiador alto, tomada USB e suporte de GPS. Fez Luanda–Namibe e Luanda–Cabinda. Revisões todas na marca.",
    imagens: ["tenere"],
    vendedor: { nome: "Miguel Sousa", verificado: true, desde: 2021, anuncios: 5, avaliacao: 5 },
    publicado: "2026-11-04",
    visualizacoes: 2170,
  },
  {
    id: "mkt-006",
    titulo: "Botas Alpinestars Tech 7 — 43",
    categoria: "Equipamento",
    preco: 245000,
    negociavel: true,
    marca: "Alpinestars",
    modelo: "Tech 7",
    estado: "Bom",
    provincia: "Huíla",
    descricao:
      "Botas de motocross tamanho 43, usadas uma temporada. Fivelas todas funcionais, solas com desgaste normal. Confortáveis e ainda com muita vida.",
    imagens: ["botas"],
    vendedor: { nome: "Mário Bengui", verificado: true, desde: 2023, anuncios: 4, avaliacao: 4.6 },
    publicado: "2026-10-22",
    visualizacoes: 298,
  },
  {
    id: "mkt-007",
    titulo: "Escape Akrapovič completo — KTM 450 SX-F",
    categoria: "Peças",
    preco: 620000,
    negociavel: false,
    marca: "Akrapovič",
    estado: "Como nova",
    provincia: "Luanda",
    descricao:
      "Sistema completo em titânio para KTM 450 SX-F (2019-2023). Usado em duas provas. Ganho real de potência e menos 1,4 kg face ao original. Inclui todas as juntas.",
    imagens: ["escape"],
    vendedor: { nome: "Eduardo Neto", verificado: true, desde: 2023, anuncios: 6, avaliacao: 4.9 },
    publicado: "2026-11-01",
    visualizacoes: 512,
  },
  {
    id: "mkt-008",
    titulo: "Suzuki DR 650 1998 — projecto",
    categoria: "Motas",
    preco: 1350000,
    negociavel: true,
    marca: "Suzuki",
    modelo: "DR 650",
    ano: 1998,
    quilometragem: 62000,
    estado: "Para peças",
    provincia: "Huambo",
    descricao:
      "Mota a precisar de restauro. Motor arranca e trabalha, mas precisa de revisão. Chassis são, sem corrosão grave. Ideal para quem quer um projecto de inverno. Documentação disponível.",
    imagens: ["dr650"],
    vendedor: { nome: "Nuno Chivela", verificado: true, desde: 2024, anuncios: 2, avaliacao: 4.5 },
    publicado: "2026-10-18",
    visualizacoes: 674,
  },
  {
    id: "mkt-009",
    titulo: "Kit de plásticos Polisport — Honda CRF 250",
    categoria: "Peças",
    preco: 95000,
    negociavel: false,
    marca: "Polisport",
    estado: "Nova",
    provincia: "Cabinda",
    descricao:
      "Kit completo de plásticos novo, na caixa, para Honda CRF 250R 2018-2021. Cor vermelha original. Comprei e vendi a mota antes de montar.",
    imagens: ["plasticos"],
    vendedor: { nome: "Hélder Quissanga", verificado: true, desde: 2023, anuncios: 3, avaliacao: 4.8 },
    publicado: "2026-11-03",
    visualizacoes: 187,
  },
  {
    id: "mkt-010",
    titulo: "Equipamento completo Thor — calças 32 + camisola M",
    categoria: "Equipamento",
    preco: 130000,
    negociavel: true,
    marca: "Thor",
    estado: "Bom",
    provincia: "Benguela",
    descricao:
      "Conjunto de calças (tamanho 32) e camisola (M) da Thor, modelo Sector. Usado uma temporada, sem rasgões. Lavado e pronto a usar.",
    imagens: ["equipamento"],
    vendedor: { nome: "Joana Ferraz", verificado: true, desde: 2022, anuncios: 8, avaliacao: 5 },
    publicado: "2026-10-26",
    visualizacoes: 405,
  },
  {
    id: "mkt-011",
    titulo: "Suporte de box e rampa de carga",
    categoria: "Acessórios",
    preco: 78000,
    negociavel: true,
    marca: "Genérico",
    estado: "Muito bom",
    provincia: "Luanda",
    descricao:
      "Suporte de box em alumínio, regulável em altura, e rampa de carga dobrável para carrinha. Ambos em bom estado, usados numa temporada.",
    imagens: ["suporte"],
    vendedor: { nome: "Lobito Motorsport", verificado: true, desde: 2023, anuncios: 11, avaliacao: 4.9 },
    publicado: "2026-10-20",
    visualizacoes: 233,
  },
  {
    id: "mkt-012",
    titulo: "Husqvarna FE 350 2020 — enduro",
    categoria: "Motas",
    preco: 4900000,
    negociavel: true,
    marca: "Husqvarna",
    modelo: "FE 350",
    ano: 2020,
    quilometragem: 6800,
    estado: "Bom",
    provincia: "Namibe",
    descricao:
      "Enduro homologada para estrada, usada em provas do calendário nacional. Motor com revisão feita, embraiagem nova. Vendo por mudança de cilindrada. Acompanha jogo de pneus de dunas.",
    imagens: ["fe350"],
    vendedor: { nome: "Paulo Tembo", verificado: true, desde: 2023, anuncios: 1, avaliacao: 4.7 },
    publicado: "2026-10-15",
    visualizacoes: 1058,
  },
];

/* ============================================================
   FÓRUM
   ============================================================ */

export const categoriasForum: CategoriaForum[] = [
  {
    slug: "competicao",
    nome: "Competição",
    descricao: "Campeonato nacional, provas, resultados e análise",
    icone: "trophy",
    topicos: 284,
    mensagens: 3921,
    cor: "#e10600",
  },
  {
    slug: "mecanica",
    nome: "Mecânica e Afinações",
    descricao: "Manutenção, avarias, afinações e preparação",
    icone: "wrench",
    topicos: 512,
    mensagens: 7840,
    cor: "#f59e0b",
  },
  {
    slug: "passeios",
    nome: "Passeios e Trilhos",
    descricao: "Organização de passeios, roteiros e travessias",
    icone: "map",
    topicos: 198,
    mensagens: 2451,
    cor: "#22c55e",
  },
  {
    slug: "equipamento",
    nome: "Equipamento",
    descricao: "Capacetes, protecções, vestuário e recomendações",
    icone: "shield",
    topicos: 167,
    mensagens: 1988,
    cor: "#0ea5e9",
  },
  {
    slug: "novatos",
    nome: "Novatos",
    descricao: "Primeiras motas, cartas de condução e dúvidas básicas",
    icone: "help",
    topicos: 341,
    mensagens: 4102,
    cor: "#a855f7",
  },
  {
    slug: "geral",
    nome: "Conversa Geral",
    descricao: "Tudo o resto sobre o mundo motard angolano",
    icone: "chat",
    topicos: 429,
    mensagens: 6337,
    cor: "#64748b",
  },
];

export const topicos: TopicoForum[] = [
  {
    id: "t-001",
    titulo: "[OFICIAL] Regras do fórum Motobox — ler antes de publicar",
    categoria: "Conversa Geral",
    categoriaSlug: "geral",
    autor: "Sofia Mussungo",
    autorAvatar: "SM",
    avatarCor: "#e10600",
    criado: "2026-01-08",
    respostas: 12,
    visualizacoes: 8940,
    ultimaResposta: { autor: "Moderação", quando: "há 2 semanas" },
    fixado: true,
    bloqueado: true,
    excerto:
      "Bem-vindos ao fórum da Motobox. Este é um espaço para a comunidade motard angolana. Respeito acima de tudo, sem publicidade não autorizada e sem conteúdo fora do tema.",
  },
  {
    id: "t-002",
    titulo: "Quem ganha o campeonato na Caála? Deixem aqui o vosso palpite",
    categoria: "Competição",
    categoriaSlug: "competicao",
    autor: "Bino_MX",
    autorAvatar: "BM",
    avatarCor: "#0ea5e9",
    criado: "2026-11-06",
    respostas: 87,
    visualizacoes: 3420,
    ultimaResposta: { autor: "TchipaFan12", quando: "há 34 minutos" },
    fixado: true,
    excerto:
      "13 pontos entre o Kiala e o Tchipa, com pontuação a dobrar. Isto vai ser decidido na última manga. O meu palpite: Tchipa ganha as duas mangas e leva o título por 3 pontos.",
  },
  {
    id: "t-003",
    titulo: "CRF 250 a falhar a quente depois de 20 minutos — já tentei tudo",
    categoria: "Mecânica e Afinações",
    categoriaSlug: "mecanica",
    autor: "Zeca_Lobito",
    autorAvatar: "ZL",
    avatarCor: "#f59e0b",
    criado: "2026-11-05",
    respostas: 23,
    visualizacoes: 890,
    ultimaResposta: { autor: "MecanicoDoBairro", quando: "há 3 horas" },
    resolvido: true,
    excerto:
      "A mota trabalha bem a frio, mas passados uns 20 minutos começa a falhar e a cortar. Já mudei vela, limpei carburador e verifiquei filtro. Alguém já passou por isto?",
  },
  {
    id: "t-004",
    titulo: "Travessia Luanda → Namibe em Janeiro: quem alinha?",
    categoria: "Passeios e Trilhos",
    categoriaSlug: "passeios",
    autor: "MiguelTrail",
    autorAvatar: "MT",
    avatarCor: "#22c55e",
    criado: "2026-11-04",
    respostas: 41,
    visualizacoes: 1560,
    ultimaResposta: { autor: "AnaOnTwo", quando: "há 5 horas" },
    excerto:
      "Estou a organizar uma travessia de 5 dias até ao Namibe, saída de Luanda a 15 de Janeiro. Percurso misto, alcatrão e picada. Já somos 6. Vagas para mais 8.",
  },
  {
    id: "t-005",
    titulo: "Primeira mota: 125 ou vou logo para uma 250?",
    categoria: "Novatos",
    categoriaSlug: "novatos",
    autor: "JoaoPrimeiraMota",
    autorAvatar: "JP",
    avatarCor: "#a855f7",
    criado: "2026-11-03",
    respostas: 56,
    visualizacoes: 2180,
    ultimaResposta: { autor: "VeteranoDoKilamba", quando: "há 8 horas" },
    excerto:
      "Tenho 19 anos, acabei de tirar a carta e quero começar no off-road. Toda a gente me diz coisas diferentes. Vale a pena começar numa 125 ou perco tempo e dinheiro?",
  },
  {
    id: "t-006",
    titulo: "Capacetes com certificação ECE 22.06 — onde comprar em Luanda?",
    categoria: "Equipamento",
    categoriaSlug: "equipamento",
    autor: "SegurancaPrimeiro",
    autorAvatar: "SP",
    avatarCor: "#0ea5e9",
    criado: "2026-11-01",
    respostas: 19,
    visualizacoes: 740,
    ultimaResposta: { autor: "CapacetesAO", quando: "há 1 dia" },
    excerto:
      "Ando à procura de um capacete com certificação nova e não quero comprar cópia. Alguém sabe que lojas em Luanda têm stock com certificação verificável?",
  },
  {
    id: "t-007",
    titulo: "Afinação de suspensão para o circuito da Caála — partilha de valores",
    categoria: "Mecânica e Afinações",
    categoriaSlug: "mecanica",
    autor: "Bruno_T12",
    autorAvatar: "BT",
    avatarCor: "#e10600",
    criado: "2026-10-30",
    respostas: 34,
    visualizacoes: 1920,
    ultimaResposta: { autor: "KilambaWrench", quando: "há 1 dia" },
    excerto:
      "Como sempre antes da final, deixo aqui os valores que uso na Caála para quem quiser experimentar. Compressão baixa 12 cliques, alta 1.5 voltas, extensão 14.",
  },
  {
    id: "t-008",
    titulo: "Onde treinar motocross em Luanda ao fim-de-semana?",
    categoria: "Novatos",
    categoriaSlug: "novatos",
    autor: "NovoNaCidade",
    autorAvatar: "NC",
    avatarCor: "#64748b",
    criado: "2026-10-29",
    respostas: 28,
    visualizacoes: 1340,
    ultimaResposta: { autor: "Bino_MX", quando: "há 2 dias" },
    excerto:
      "Mudei-me há pouco para Luanda e trouxe a mota. Onde é que se treina por aqui sem ser em terrenos privados? O Kilamba está aberto durante a semana?",
  },
  {
    id: "t-009",
    titulo: "Balanço da temporada 2026: o que correu bem e o que tem de melhorar",
    categoria: "Competição",
    categoriaSlug: "competicao",
    autor: "AnalistaMX",
    autorAvatar: "AM",
    avatarCor: "#e10600",
    criado: "2026-10-27",
    respostas: 62,
    visualizacoes: 2610,
    ultimaResposta: { autor: "Sofia Mussungo", quando: "há 2 dias" },
    excerto:
      "Cinco rondas, três disciplinas e um campeonato em aberto até ao fim. Mas continuamos com problemas de cronometragem e falta de balneários em metade das provas. Vamos falar a sério.",
  },
  {
    id: "t-010",
    titulo: "Vendo material do meu filho que deixou de correr — dúvida sobre o marketplace",
    categoria: "Conversa Geral",
    categoriaSlug: "geral",
    autor: "PaiDoPiloto",
    autorAvatar: "PP",
    avatarCor: "#f59e0b",
    criado: "2026-10-25",
    respostas: 8,
    visualizacoes: 420,
    ultimaResposta: { autor: "Moderação", quando: "há 3 dias" },
    resolvido: true,
    excerto:
      "Como faço para ficar verificado no marketplace? Tenho equipamento e uma mota para vender e queria fazer isso pela plataforma em vez do grupo do WhatsApp.",
  },
];

/* ============================================================
   HELPERS
   ============================================================ */

export function formatKz(valor: number): string {
  return new Intl.NumberFormat("pt-AO", { maximumFractionDigits: 0 }).format(valor) + " Kz";
}

/*
 * As datas saem sempre em português: são formatadas no servidor, onde o
 * idioma escolhido pelo visitante ainda não é conhecido. A tradução para
 * inglês é feita no cliente, em components/TraduzirPagina.tsx.
 */
const localeData = "pt-PT";

export function formatData(iso: string, opts?: Intl.DateTimeFormatOptions): string {
  return new Date(iso).toLocaleDateString(localeData, opts ?? { day: "2-digit", month: "long", year: "numeric" });
}

export function formatDataCurta(iso: string): string {
  return new Date(iso).toLocaleDateString(localeData, { day: "2-digit", month: "short" }).toUpperCase().replace(".", "");
}

export function classificacaoPilotos(categoria?: string) {
  return [...pilotos]
    .filter((p) => !categoria || categoria === "Todas" || p.categoria === categoria)
    .sort((a, b) => b.estatisticas.pontos - a.estatisticas.pontos)
    .map((p, i) => ({ ...p, posicao: i + 1 }));
}

export function classificacaoEquipas() {
  return [...equipas]
    .filter((e) => e.estatisticas.pontos > 0)
    .sort((a, b) => b.estatisticas.pontos - a.estatisticas.pontos)
    .map((e, i) => ({ ...e, posicao: i + 1 }));
}

export function proximoEvento(): Evento | undefined {
  const agora = Date.now();
  return eventos
    .filter((e) => new Date(e.dataInicio).getTime() > agora)
    .sort((a, b) => +new Date(a.dataInicio) - +new Date(b.dataInicio))[0];
}

export function eventosComBilhetes(): Evento[] {
  return eventos.filter((e) => e.bilhetes && e.bilhetes.length > 0 && e.estado !== "concluido");
}

export function getEvento(slug: string) {
  return eventos.find((e) => e.slug === slug);
}
export function getPiloto(slug: string) {
  return pilotos.find((p) => p.slug === slug);
}
export function getEquipa(slug: string) {
  return equipas.find((e) => e.slug === slug);
}
export function getNoticia(slug: string) {
  return noticias.find((n) => n.slug === slug);
}
export function getAnuncio(id: string) {
  return anuncios.find((a) => a.id === id);
}
export function getTopico(id: string) {
  return topicos.find((t) => t.id === id);
}
