/**
 * Créditos das fotografias do site.
 *
 * Todas as chaves de lib/imagens.ts apontam para fotografias publicadas no
 * Instagram da MotoBox (@motobox_angola) ou nas contas dos clubes. Cada
 * fotografia foi copiada para o Supabase Storage (bucket "media") com o nome
 * `instagram-<código da publicação>-<n.º da imagem no carrossel>.jpg`; alguns
 * ficheiros foram recortados para tirar texto, logótipos ou molduras da
 * publicação (está dito na descrição).
 *
 * Esta lista é só para consulta da equipa (de onde vem cada imagem e o que
 * mostra); o site não a lê. 93 fotografias, de 12 contas:
 * @motobox_angola (44), @motardsangola (7), @performancebikers2015 (7), @amigosdapicada (6), @tuaregs_motard_angola (6), @africannomadas (5), @elite_motard_angola (5), @ladies_riders_ao (4), @vespa_angola (4), @300km_a_norte (2), @nomadasangola (2), @clube.anjos.bantu (1).
 */

export interface FotoInstagram {
  /** Chaves de lib/imagens.ts que usam a fotografia ("banner-…" para as aberturas). */
  chaves: string[];
  /** Caminho no bucket "media" do Supabase Storage. */
  ficheiro: string;
  /** Conta que publicou. */
  conta: string;
  /** Publicação de origem. */
  publicacao: string;
  /** Posição da imagem no carrossel (1 numa publicação simples). */
  imagem: number;
  /** Data da publicação (AAAA-MM-DD). */
  data: string;
  /** O que a fotografia mostra. */
  descricao: string;
}

/** Vídeo de fundo do site (ENTRADA_PADRAO em lib/conteudo/grupos/site.ts). */
export const VIDEO_INSTAGRAM = {
  ficheiro: "videos/instagram-DdwTCnFOtxr-fundo-calmo.mp4",
  poster: "videos/instagram-DdwTCnFOtxr-fundo-calmo.jpg",
  conta: "@motobox_angola",
  publicacao: "https://www.instagram.com/p/DdwTCnFOtxr/",
  data: "2026-09-26",
  descricao:
    "7.ª prova do Campeonato de Motocross nas dunas: quatro planos longos e abertos, a metade da velocidade, com transições suaves e sem cortes bruscos, clarões nem caras; sem a marca do fotógrafo. Vídeo calmo para o fundo do site (substitui o resumo da 8.ª prova, que tinha movimento a mais).",
};

export const FOTOS_INSTAGRAM: FotoInstagram[] = [
  {
    chaves: ["kilamba"],
    ficheiro: "imagens/instagram-DSKHLvuDGe4-3.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DSKHLvuDGe4/",
    imagem: 3,
    data: "2025-12-12",
    descricao: "Piloto de motocross de azul em curva, com os pneus brancos da pista atrás (Grande Final, Dezembro de 2025)",
  },
  {
    chaves: ["huambo"],
    ficheiro: "imagens/instagram-DSKHLvuDGe4-8.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DSKHLvuDGe4/",
    imagem: 8,
    data: "2025-12-12",
    descricao: "Piloto de motocross em velocidade, fotografado em arrasto (Grande Final, Dezembro de 2025)",
  },
  {
    chaves: ["dakar"],
    ficheiro: "imagens/instagram-DTcnUPYDgQk-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DTcnUPYDgQk/",
    imagem: 1,
    data: "2026-01-13",
    descricao: "SSV a levantar terra numa pista de terra vermelha (recorte, sem a marca da MotoBox)",
  },
  {
    chaves: ["desportivas"],
    ficheiro: "imagens/instagram-DUFnyinjlp1-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DUFnyinjlp1/",
    imagem: 1,
    data: "2026-01-29",
    descricao: "Motard de capacete numa desportiva, de faróis acesos, numa rua de Luanda (Ubuntu 2026)",
  },
  {
    chaves: ["banner-sobre"],
    ficheiro: "imagens/instagram-DW_LM6gDJlC-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DW_LM6gDJlC/",
    imagem: 1,
    data: "2026-04-11",
    descricao: "Pórtico da META no Circuito Jorge Varela, com bandeiras de Angola e céu azul",
  },
  {
    chaves: ["capacete", "artigo-capacete"],
    ficheiro: "imagens/instagram-DXFD2QqDNf8-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DXFD2QqDNf8/",
    imagem: 1,
    data: "2026-04-13",
    descricao: "Piloto de capacete laranja e óculos, em grande plano, na pista",
  },
  {
    chaves: ["joana-ferraz"],
    ficheiro: "imagens/instagram-DXFD2QqDNf8-2.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DXFD2QqDNf8/",
    imagem: 2,
    data: "2026-04-13",
    descricao: "Piloto numa Yamaha azul em curva, entre os pneus da pista",
  },
  {
    chaves: ["adilson-mbala"],
    ficheiro: "imagens/instagram-DXFD2QqDNf8-3.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DXFD2QqDNf8/",
    imagem: 3,
    data: "2026-04-13",
    descricao: "Dois pilotos em curva na pista de terra, com uma Yamaha azul à frente",
  },
  {
    chaves: ["moto-4-kilamba", "moto-4-kilamba-2026"],
    ficheiro: "imagens/instagram-DXFD2QqDNf8-4.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DXFD2QqDNf8/",
    imagem: 4,
    data: "2026-04-13",
    descricao: "Moto 4 em pleno salto, contra o céu azul",
  },
  {
    chaves: ["mxgp"],
    ficheiro: "imagens/instagram-DXOgXAkjGzU-2.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DXOgXAkjGzU/",
    imagem: 2,
    data: "2026-04-17",
    descricao: "Piloto de motocross em salto, contra um céu azul com nuvens (fotografia de @khalilsilva_fotografo)",
  },
  {
    chaves: ["artigo-primeira-mota"],
    ficheiro: "imagens/instagram-DXOgXAkjGzU-4.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DXOgXAkjGzU/",
    imagem: 4,
    data: "2026-04-17",
    descricao: "Jovem piloto de vermelho numa mota pequena, na poeira da pista (fotografia de @khalilsilva_fotografo)",
  },
  {
    chaves: ["custom"],
    ficheiro: "imagens/instagram-DXl9OEsjPYs-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DXl9OEsjPYs/",
    imagem: 1,
    data: "2026-04-26",
    descricao: "«Motoqueiro Fantasma»: motard de máscara de caveira numa chopper (preto e branco)",
  },
  {
    chaves: ["novatos"],
    ficheiro: "imagens/instagram-DX1mrF1DDPg-2.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DX1mrF1DDPg/",
    imagem: 2,
    data: "2026-05-02",
    descricao: "Jovem piloto numa mota pequena, na curva da pista",
  },
  {
    chaves: ["equipamento"],
    ficheiro: "imagens/instagram-DX1mrF1DDPg-3.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DX1mrF1DDPg/",
    imagem: 3,
    data: "2026-05-02",
    descricao: "Piloto de equipamento completo numa Yamaha azul, em curva",
  },
  {
    chaves: ["silvio-domingos"],
    ficheiro: "imagens/instagram-DX1mrF1DDPg-4.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DX1mrF1DDPg/",
    imagem: 4,
    data: "2026-05-02",
    descricao: "Piloto de motocross de capacete, em curva na terra vermelha",
  },
  {
    chaves: ["moto-4"],
    ficheiro: "imagens/instagram-DYALZYxDJIZ-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DYALZYxDJIZ/",
    imagem: 1,
    data: "2026-05-06",
    descricao: "Moto 4 numa nuvem de poeira",
  },
  {
    chaves: ["banner-contacto"],
    ficheiro: "imagens/instagram-DYwhrpGuYR0-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DYwhrpGuYR0/",
    imagem: 1,
    data: "2026-05-25",
    descricao: "Embondeiro ao pôr do sol (Dia de África; recorte, sem o logótipo)",
  },
  {
    chaves: ["encontro-motobox-marginal", "classica", "classicas"],
    ficheiro: "imagens/instagram-DaqgievjrnF-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DaqgievjrnF/",
    imagem: 1,
    data: "2026-07-11",
    descricao: "Harley-Davidson à frente da coluna, numa avenida de Luanda, no Dia do Motard Angolano",
  },
  {
    chaves: ["artigo-dia-do-motard"],
    ficheiro: "imagens/instagram-DaqgievjrnF-4.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DaqgievjrnF/",
    imagem: 4,
    data: "2026-07-11",
    descricao: "Motard de costas, de colete, com a bandeira da Tribo do 11 de Novembro, no Dia do Motard",
  },
  {
    chaves: ["banner-eventos"],
    ficheiro: "imagens/instagram-DbfmkCCDm2b-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DbfmkCCDm2b/",
    imagem: 1,
    data: "2026-08-01",
    descricao: "Coluna de motas de turismo numa avenida de Luanda, no Dia do Motard Angolano",
  },
  {
    chaves: ["dia-do-motard-angolano-2026"],
    ficheiro: "imagens/instagram-DbfmkCCDm2b-2.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DbfmkCCDm2b/",
    imagem: 2,
    data: "2026-08-01",
    descricao: "Coluna de motas a chegar, de faróis acesos, no Dia do Motard Angolano",
  },
  {
    chaves: ["geral"],
    ficheiro: "imagens/instagram-DbfmkCCDm2b-3.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DbfmkCCDm2b/",
    imagem: 3,
    data: "2026-08-01",
    descricao: "BMW GS com bandeira, a subir uma encosta no Dia do Motard Angolano",
  },
  {
    chaves: ["cidade"],
    ficheiro: "imagens/instagram-DbfmkCCDm2b-4.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DbfmkCCDm2b/",
    imagem: 4,
    data: "2026-08-01",
    descricao: "Ducati vermelha e outras motas no desfile do Dia do Motard Angolano",
  },
  {
    chaves: ["banner-seguranca"],
    ficheiro: "imagens/instagram-DbfmkCCDm2b-5.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DbfmkCCDm2b/",
    imagem: 5,
    data: "2026-08-01",
    descricao: "Motard de capacete com uma bandeira, na estrada, no Dia do Motard Angolano",
  },
  {
    chaves: ["mecanica", "suporte"],
    ficheiro: "imagens/instagram-DcEhdn5DghP-1.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DcEhdn5DghP/",
    imagem: 1,
    data: "2026-08-15",
    descricao: "Mota de motocross 85 cc exposta num pedestal (recorte)",
  },
  {
    chaves: ["escape"],
    ficheiro: "imagens/instagram-DcEhdn5DghP-6.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DcEhdn5DghP/",
    imagem: 6,
    data: "2026-08-15",
    descricao: "Escape e motor da mota de motocross 85 cc exposta (recorte)",
  },
  {
    chaves: ["plasticos"],
    ficheiro: "imagens/instagram-DcEhdn5DghP-7.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DcEhdn5DghP/",
    imagem: 7,
    data: "2026-08-15",
    descricao: "Plásticos e decoração da mota de motocross 85 cc exposta (recorte)",
  },
  {
    chaves: ["suspensao", "oficina-aberta-mecanica-basica"],
    ficheiro: "imagens/instagram-DcEhdn5DghP-8.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DcEhdn5DghP/",
    imagem: 8,
    data: "2026-08-15",
    descricao: "Suspensão e roda da frente da mota de motocross 85 cc exposta (recorte)",
  },
  {
    chaves: ["rui-katchimba"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-11.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 11,
    data: "2026-09-21",
    descricao: "Piloto numa Kawasaki verde, a levantar poeira (prova do Cuanza Sul)",
  },
  {
    chaves: ["paulo-tembo"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-12.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 12,
    data: "2026-09-21",
    descricao: "Piloto em curva na pista de terra seca, com o público ao fundo (Cuanza Sul)",
  },
  {
    chaves: ["ktm"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-14.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 14,
    data: "2026-09-21",
    descricao: "Piloto em curva numa nuvem de poeira (Cuanza Sul)",
  },
  {
    chaves: ["ivandro-cabral"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-15.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 15,
    data: "2026-09-21",
    descricao: "Piloto de vermelho numa mota verde, entre as colinas (Cuanza Sul)",
  },
  {
    chaves: ["ktm250"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-16.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 16,
    data: "2026-09-21",
    descricao: "Piloto em salto, ao longe, na pista de terra (Cuanza Sul)",
  },
  {
    chaves: ["lubango"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-17.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 17,
    data: "2026-09-21",
    descricao: "Piloto na poeira de uma pista entre colinas secas (Cuanza Sul)",
  },
  {
    chaves: ["helder-quissanga"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-18.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 18,
    data: "2026-09-21",
    descricao: "Piloto numa Kawasaki verde, com as colinas atrás (Cuanza Sul)",
  },
  {
    chaves: ["competicao"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-19.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 19,
    data: "2026-09-21",
    descricao: "Dois pilotos de motocross, um deles em salto (Cuanza Sul)",
  },
  {
    chaves: ["tundavala"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-20.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 20,
    data: "2026-09-21",
    descricao: "Piloto a descer a encosta numa nuvem de poeira (Cuanza Sul)",
  },
  {
    chaves: ["banner-artigos"],
    ficheiro: "imagens/instagram-DdjRu2YjDrX-6.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DdjRu2YjDrX/",
    imagem: 6,
    data: "2026-09-21",
    descricao: "Pilotos de capacete alinhados na grelha de partida (Cuanza Sul)",
  },
  {
    chaves: ["botas"],
    ficheiro: "imagens/instagram-DeG034qDmZW-11.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DeG034qDmZW/",
    imagem: 11,
    data: "2026-10-05",
    descricao: "Botas e mota de um piloto parado na grelha (recorte, 8.ª prova)",
  },
  {
    chaves: ["eduardo-neto"],
    ficheiro: "imagens/instagram-DeG034qDmZW-2.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DeG034qDmZW/",
    imagem: 2,
    data: "2026-10-05",
    descricao: "Piloto de amarelo e azul em curva na terra vermelha (8.ª prova do Campeonato)",
  },
  {
    chaves: ["nelson-kiala"],
    ficheiro: "imagens/instagram-DeG034qDmZW-3.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DeG034qDmZW/",
    imagem: 3,
    data: "2026-10-05",
    descricao: "Piloto de vermelho em curva, com outro piloto atrás (8.ª prova do Campeonato)",
  },
  {
    chaves: ["bruno-tchipa"],
    ficheiro: "imagens/instagram-DeG034qDmZW-4.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DeG034qDmZW/",
    imagem: 4,
    data: "2026-10-05",
    descricao: "Piloto de vermelho em salto, com casas ao fundo (8.ª prova do Campeonato)",
  },
  {
    chaves: ["mario-bengui"],
    ficheiro: "imagens/instagram-DeG034qDmZW-5.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DeG034qDmZW/",
    imagem: 5,
    data: "2026-10-05",
    descricao: "Piloto em salto, contra o céu (8.ª prova do Campeonato)",
  },
  {
    chaves: ["crf450"],
    ficheiro: "imagens/instagram-DeG034qDmZW-9.jpg",
    conta: "@motobox_angola",
    publicacao: "https://www.instagram.com/p/DeG034qDmZW/",
    imagem: 9,
    data: "2026-10-05",
    descricao: "Dois pilotos em curva, com os pneus brancos e o público atrás (8.ª prova do Campeonato)",
  },
  {
    chaves: ["clube-300-km-a-norte"],
    ficheiro: "imagens/instagram-CoLjbIvsalB-1.jpg",
    conta: "@300km_a_norte",
    publicacao: "https://www.instagram.com/p/CoLjbIvsalB/",
    imagem: 1,
    data: "2023-02-03",
    descricao: "Ubuntu 2023: a coluna de motas a descer uma avenida de Luanda, vista de cima",
  },
  {
    chaves: ["banner-legal"],
    ficheiro: "imagens/instagram-Co8KkeJM9XI-4.jpg",
    conta: "@300km_a_norte",
    publicacao: "https://www.instagram.com/p/Co8KkeJM9XI/",
    imagem: 4,
    data: "2023-02-21",
    descricao: "Vista do alto sobre a mata do Zaire, na viagem às Grutas do Zau Weva e à foz do Mucula",
  },
  {
    chaves: ["painel-clubes"],
    ficheiro: "imagens/instagram-C2IbIXLIvYx-3.jpg",
    conta: "@africannomadas",
    publicacao: "https://www.instagram.com/p/C2IbIXLIvYx/",
    imagem: 3,
    data: "2024-01-15",
    descricao: "Membros dos African Nómadas, de costas, sob a faixa «Liberdade sobre rodas, vamos que vamos»",
  },
  {
    chaves: ["banner-marketplace"],
    ficheiro: "imagens/instagram-C2PgSGss_XY-3.jpg",
    conta: "@africannomadas",
    publicacao: "https://www.instagram.com/p/C2PgSGss_XY/",
    imagem: 3,
    data: "2024-01-18",
    descricao: "Fila de motas de turismo estacionadas numa rua do Lobito",
  },
  {
    chaves: ["clube-african-nomadas"],
    ficheiro: "imagens/instagram-C2PgSGss_XY-4.jpg",
    conta: "@africannomadas",
    publicacao: "https://www.instagram.com/p/C2PgSGss_XY/",
    imagem: 4,
    data: "2024-01-18",
    descricao: "Rua do Lobito com palmeiras e uma fila de motas do clube à porta de um restaurante",
  },
  {
    chaves: ["banner-clubes"],
    ficheiro: "imagens/instagram-C2PgSGss_XY-5.jpg",
    conta: "@africannomadas",
    publicacao: "https://www.instagram.com/p/C2PgSGss_XY/",
    imagem: 5,
    data: "2024-01-18",
    descricao: "Fila de motas no Lobito, com uma Honda azul à frente",
  },
  {
    chaves: ["painel-sobre"],
    ficheiro: "imagens/instagram-C2PgSGss_XY-6.jpg",
    conta: "@africannomadas",
    publicacao: "https://www.instagram.com/p/C2PgSGss_XY/",
    imagem: 6,
    data: "2024-01-18",
    descricao: "Motards à conversa junto às motas estacionadas, à porta de um restaurante no Lobito",
  },
  {
    chaves: ["artigo-amigos-da-picada"],
    ficheiro: "imagens/instagram-DLPZ6uHMcCx-1.jpg",
    conta: "@amigosdapicada",
    publicacao: "https://www.instagram.com/p/DLPZ6uHMcCx/",
    imagem: 1,
    data: "2025-06-23",
    descricao: "Caravana dos Amigos da Picada numa avenida de Sevilha, no Raid Ibérico de 2024",
  },
  {
    chaves: ["banner-importar"],
    ficheiro: "imagens/instagram-DMxwIL9NTkr-5.jpg",
    conta: "@amigosdapicada",
    publicacao: "https://www.instagram.com/p/DMxwIL9NTkr/",
    imagem: 5,
    data: "2025-07-31",
    descricao: "Motards na fronteira de Espanha, junto à placa da alfândega, no Raid Catalunha 2025",
  },
  {
    chaves: ["artigo-mota-usada"],
    ficheiro: "imagens/instagram-DaKjfkWsfFU-1.jpg",
    conta: "@amigosdapicada",
    publicacao: "https://www.instagram.com/p/DaKjfkWsfFU/",
    imagem: 1,
    data: "2026-06-29",
    descricao: "Honda Africa Twin estacionada, carregada para a viagem de Angola a Moçambique",
  },
  {
    chaves: ["clube-amigos-da-picada"],
    ficheiro: "imagens/instagram-Dby44iSnCiV-1.jpg",
    conta: "@amigosdapicada",
    publicacao: "https://www.instagram.com/p/Dby44iSnCiV/",
    imagem: 1,
    data: "2026-08-08",
    descricao: "Três membros de costas, de blusão com «Angola» nas costas, na festa dos 20 anos (preto e branco)",
  },
  {
    chaves: ["noite"],
    ficheiro: "imagens/instagram-Dby44iSnCiV-6.jpg",
    conta: "@amigosdapicada",
    publicacao: "https://www.instagram.com/p/Dby44iSnCiV/",
    imagem: 6,
    data: "2026-08-08",
    descricao: "Fila de motas estacionadas à noite, na festa dos 20 anos dos Amigos da Picada",
  },
  {
    chaves: ["gala"],
    ficheiro: "imagens/instagram-Dby44iSnCiV-7.jpg",
    conta: "@amigosdapicada",
    publicacao: "https://www.instagram.com/p/Dby44iSnCiV/",
    imagem: 7,
    data: "2026-08-08",
    descricao: "Palco com luzes e ecrã em xadrez, no concerto da festa dos 20 anos dos Amigos da Picada",
  },
  {
    chaves: ["clube-anjos-bantu"],
    ficheiro: "imagens/instagram-DWPOelXjkL8-8.jpg",
    conta: "@clube.anjos.bantu",
    publicacao: "https://www.instagram.com/p/DWPOelXjkL8/",
    imagem: 8,
    data: "2026-03-23",
    descricao: "Motas do clube estacionadas à sombra de árvores, numa paragem do passeio",
  },
  {
    chaves: ["artigo-300-km"],
    ficheiro: "imagens/instagram-ClE15vph_gI-2.jpg",
    conta: "@elite_motard_angola",
    publicacao: "https://www.instagram.com/p/ClE15vph_gI/",
    imagem: 2,
    data: "2022-11-17",
    descricao: "Dois motards equipados junto ao muro «Sejam bem-vindos a UPP-Zaire, Soyo», no Raid Soyo",
  },
  {
    chaves: ["trail"],
    ficheiro: "imagens/instagram-ClE1sQJBcQo-1.jpg",
    conta: "@elite_motard_angola",
    publicacao: "https://www.instagram.com/p/ClE1sQJBcQo/",
    imagem: 1,
    data: "2022-11-17",
    descricao: "Motard de capacete numa Honda Africa Twin, no Raid Soyo",
  },
  {
    chaves: ["costa-de-benguela"],
    ficheiro: "imagens/instagram-ClE2xbmBYXh-5.jpg",
    conta: "@elite_motard_angola",
    publicacao: "https://www.instagram.com/p/ClE2xbmBYXh/",
    imagem: 5,
    data: "2022-11-17",
    descricao: "Grupo de motards em cima das letras gigantes de BENGUELA, no Raid Benguela",
  },
  {
    chaves: ["passeio-miradouro-da-lua", "miradouro-da-lua", "estrada-da-costa"],
    ficheiro: "imagens/instagram-ClE3S7FBb1l-3.jpg",
    conta: "@elite_motard_angola",
    publicacao: "https://www.instagram.com/p/ClE3S7FBb1l/",
    imagem: 3,
    data: "2022-11-17",
    descricao: "Paragem na EN100, junto à placa com Porto Amboim, Sumbe e Lobito, no Raid Benguela",
  },
  {
    chaves: ["clube-elite-motard"],
    ficheiro: "imagens/instagram-ClE3S7FBb1l-4.jpg",
    conta: "@elite_motard_angola",
    publicacao: "https://www.instagram.com/p/ClE3S7FBb1l/",
    imagem: 4,
    data: "2022-11-17",
    descricao: "Motard de capacete numa Africa Twin vermelha, à beira de um capinzal, no Raid Benguela",
  },
  {
    chaves: ["namibe", "deserto-do-namibe"],
    ficheiro: "imagens/instagram-DBvc8neIInk-1.jpg",
    conta: "@ladies_riders_ao",
    publicacao: "https://www.instagram.com/p/DBvc8neIInk/",
    imagem: 1,
    data: "2024-10-30",
    descricao: "Motas de viagem alinhadas no horizonte do deserto do Namibe, ao fim da tarde (recorte, sem pessoas)",
  },
  {
    chaves: ["banner-entrar"],
    ficheiro: "imagens/instagram-DFYkDtpM3Y2-5.jpg",
    conta: "@ladies_riders_ao",
    publicacao: "https://www.instagram.com/p/DFYkDtpM3Y2/",
    imagem: 5,
    data: "2025-01-28",
    descricao: "Motard de capacete parada na sua mota amarela, vista de trás",
  },
  {
    chaves: ["clube-ladies-in-2-wheels"],
    ficheiro: "imagens/instagram-DF-TKRPIq-4-1.jpg",
    conta: "@ladies_riders_ao",
    publicacao: "https://www.instagram.com/p/DF-TKRPIq-4/",
    imagem: 1,
    data: "2025-02-12",
    descricao: "Motard de costas, de capacete, ao lado da mota numa estrada ao fim da tarde",
  },
  {
    chaves: ["artigo-lady-riders"],
    ficheiro: "imagens/instagram-DVp--SuDFU5-1.jpg",
    conta: "@ladies_riders_ao",
    publicacao: "https://www.instagram.com/p/DVp--SuDFU5/",
    imagem: 1,
    data: "2026-03-09",
    descricao: "Passeio de mulheres motards numa avenida de Luanda, visto de cima",
  },
  {
    chaves: ["clube-amigos-do-capim"],
    ficheiro: "imagens/instagram-C65x4Z0sNAj-3.jpg",
    conta: "@motardsangola",
    publicacao: "https://www.instagram.com/p/C65x4Z0sNAj/",
    imagem: 3,
    data: "2024-05-13",
    descricao: "Duas motas de turismo paradas num alto de terra batida («Amigo capim»)",
  },
  {
    chaves: ["benguela", "fe350"],
    ficheiro: "imagens/instagram-DCe7tpetE5C-6.jpg",
    conta: "@motardsangola",
    publicacao: "https://www.instagram.com/p/DCe7tpetE5C/",
    imagem: 6,
    data: "2024-11-17",
    descricao: "Mota de enduro KTM parada num trilho de pedra",
  },
  {
    chaves: ["banner-forum"],
    ficheiro: "imagens/instagram-DEKpBl3NKLp-4.jpg",
    conta: "@motardsangola",
    publicacao: "https://www.instagram.com/p/DEKpBl3NKLp/",
    imagem: 4,
    data: "2024-12-29",
    descricao: "Abraço motard de final de ano, à noite, diante de um edifício iluminado em Luanda",
  },
  {
    chaves: ["clube-motards-de-angola"],
    ficheiro: "imagens/instagram-DKsU0buNEJu-1.jpg",
    conta: "@motardsangola",
    publicacao: "https://www.instagram.com/p/DKsU0buNEJu/",
    imagem: 1,
    data: "2025-06-09",
    descricao: "Coluna de motas trail numa picada de areia vermelha",
  },
  {
    chaves: ["banner-rotas"],
    ficheiro: "imagens/instagram-DKsU0buNEJu-2.jpg",
    conta: "@motardsangola",
    publicacao: "https://www.instagram.com/p/DKsU0buNEJu/",
    imagem: 2,
    data: "2025-06-09",
    descricao: "Estrada longa no planalto, vista de cima da mota",
  },
  {
    chaves: ["carlos-samba"],
    ficheiro: "imagens/instagram-DKsU0buNEJu-3.jpg",
    conta: "@motardsangola",
    publicacao: "https://www.instagram.com/p/DKsU0buNEJu/",
    imagem: 3,
    data: "2025-06-09",
    descricao: "Motard de capacete numa trail carregada, a subir um talude de terra vermelha",
  },
  {
    chaves: ["tenere"],
    ficheiro: "imagens/instagram-DZMsNT5tpvd-1.jpg",
    conta: "@motardsangola",
    publicacao: "https://www.instagram.com/p/DZMsNT5tpvd/",
    imagem: 1,
    data: "2026-06-05",
    descricao: "Yamaha Ténéré azuis estacionadas ao longo de uma parede branca",
  },
  {
    chaves: ["clube-nomadas-angola"],
    ficheiro: "imagens/instagram-B_b6bwuAYfF-1.jpg",
    conta: "@nomadasangola",
    publicacao: "https://www.instagram.com/p/B_b6bwuAYfF/",
    imagem: 1,
    data: "2020-04-26",
    descricao: "Costas de um colete de cabedal com o emblema bordado dos Nómadas",
  },
  {
    chaves: ["artigo-serra-da-leba", "raide-serra-da-leba", "serra-da-leba"],
    ficheiro: "imagens/instagram-B_pMzdugT2Z-1.jpg",
    conta: "@nomadasangola",
    publicacao: "https://www.instagram.com/p/B_pMzdugT2Z/",
    imagem: 1,
    data: "2020-05-01",
    descricao: "Coluna de motards parada nas curvas da Serra da Leba, vista de cima (recorte, sem o texto da publicação)",
  },
  {
    chaves: ["clube-performance-bikers", "banner-conta"],
    ficheiro: "imagens/instagram-DGzya6bM8j_-1.jpg",
    conta: "@performancebikers2015",
    publicacao: "https://www.instagram.com/p/DGzya6bM8j_/",
    imagem: 1,
    data: "2025-03-05",
    descricao: "Coluna de motas numa estrada longa entre o capim, vista de drone (Raid Uíge–Malanje 2025)",
  },
  {
    chaves: ["dr650"],
    ficheiro: "imagens/instagram-DLem_f1sYAq-1.jpg",
    conta: "@performancebikers2015",
    publicacao: "https://www.instagram.com/p/DLem_f1sYAq/",
    imagem: 1,
    data: "2025-06-29",
    descricao: "Motas de turismo estacionadas ao fim da tarde (recorte, sem a marca da câmara)",
  },
  {
    chaves: ["passeios"],
    ficheiro: "imagens/instagram-DT-_0YuETLc-1.jpg",
    conta: "@performancebikers2015",
    publicacao: "https://www.instagram.com/p/DT-_0YuETLc/",
    imagem: 1,
    data: "2026-01-26",
    descricao: "Coluna de motas de faróis acesos numa rua de Luanda (Ubuntu 2026)",
  },
  {
    chaves: ["artigo-kalandula", "kalandula-e-pungo-andongo"],
    ficheiro: "imagens/instagram-DW1Zt26lyG6-1.jpg",
    conta: "@performancebikers2015",
    publicacao: "https://www.instagram.com/p/DW1Zt26lyG6/",
    imagem: 1,
    data: "2026-04-07",
    descricao: "Motas do clube estacionadas sob os eucaliptos, no Cuale (Malanje)",
  },
  {
    chaves: ["artigo-chuva", "chuva"],
    ficheiro: "imagens/instagram-DW1Zt26lyG6-5.jpg",
    conta: "@performancebikers2015",
    publicacao: "https://www.instagram.com/p/DW1Zt26lyG6/",
    imagem: 5,
    data: "2026-04-07",
    descricao: "Motas estacionadas no chão molhado, sob os eucaliptos do Cuale (Malanje)",
  },
  {
    chaves: ["passeio-solidario-natal-2026"],
    ficheiro: "imagens/instagram-DW3R3ozjQcx-12.jpg",
    conta: "@performancebikers2015",
    publicacao: "https://www.instagram.com/p/DW3R3ozjQcx/",
    imagem: 12,
    data: "2026-04-08",
    descricao: "Donativos (sacos de comida e caixas) entregues pelo clube no Cuale, Malanje (recorte)",
  },
  {
    chaves: ["cabinda"],
    ficheiro: "imagens/instagram-DW3R3ozjQcx-4.jpg",
    conta: "@performancebikers2015",
    publicacao: "https://www.instagram.com/p/DW3R3ozjQcx/",
    imagem: 4,
    data: "2026-04-08",
    descricao: "Donativos entregues numa aldeia do Cuale, Malanje (recorte)",
  },
  {
    chaves: ["artigo-verificacao"],
    ficheiro: "imagens/instagram-DNdX5I9MWtz-1.jpg",
    conta: "@tuaregs_motard_angola",
    publicacao: "https://www.instagram.com/p/DNdX5I9MWtz/",
    imagem: 1,
    data: "2025-08-17",
    descricao: "Motard de capacete numa trail, parado numa bomba de gasolina",
  },
  {
    chaves: ["trail-estrada"],
    ficheiro: "imagens/instagram-DNdX5I9MWtz-2.jpg",
    conta: "@tuaregs_motard_angola",
    publicacao: "https://www.instagram.com/p/DNdX5I9MWtz/",
    imagem: 2,
    data: "2025-08-17",
    descricao: "Motard de capacete numa Kawasaki Versys, à beira da estrada",
  },
  {
    chaves: ["painel-eventos"],
    ficheiro: "imagens/instagram-DavYPd7jBW8-10.jpg",
    conta: "@tuaregs_motard_angola",
    publicacao: "https://www.instagram.com/p/DavYPd7jBW8/",
    imagem: 10,
    data: "2026-07-13",
    descricao: "Motards de capacete a acenar, no desfile do Dia do Motard Angolano",
  },
  {
    chaves: ["natal"],
    ficheiro: "imagens/instagram-DavYPd7jBW8-12.jpg",
    conta: "@tuaregs_motard_angola",
    publicacao: "https://www.instagram.com/p/DavYPd7jBW8/",
    imagem: 12,
    data: "2026-07-13",
    descricao: "Coluna de motas atrás de um jipe, numa avenida de Luanda, no Dia do Motard Angolano",
  },
  {
    chaves: ["artigo-grupo"],
    ficheiro: "imagens/instagram-DavYPd7jBW8-9.jpg",
    conta: "@tuaregs_motard_angola",
    publicacao: "https://www.instagram.com/p/DavYPd7jBW8/",
    imagem: 9,
    data: "2026-07-13",
    descricao: "Coluna de motas de faróis acesos no Dia do Motard Angolano",
  },
  {
    chaves: ["clube-tuaregs"],
    ficheiro: "imagens/instagram-DavZJwkjAQW-1.jpg",
    conta: "@tuaregs_motard_angola",
    publicacao: "https://www.instagram.com/p/DavZJwkjAQW/",
    imagem: 1,
    data: "2026-07-13",
    descricao: "Banca dos Tuaregs, com a bandeira do clube e motas, no Dia do Motard (recorte)",
  },
  {
    chaves: ["cabo-ledo-e-quicama"],
    ficheiro: "imagens/instagram-C14RJZzspq9-1.jpg",
    conta: "@vespa_angola",
    publicacao: "https://www.instagram.com/p/C14RJZzspq9/",
    imagem: 1,
    data: "2024-01-09",
    descricao: "Vespas à beira da estrada de Porto Amboim, junto a uma placa",
  },
  {
    chaves: ["vespa-amarela"],
    ficheiro: "imagens/instagram-C14RJZzspq9-2.jpg",
    conta: "@vespa_angola",
    publicacao: "https://www.instagram.com/p/C14RJZzspq9/",
    imagem: 2,
    data: "2024-01-09",
    descricao: "Vespas amarelas e vermelhas paradas à porta de uma loja, a caminho de Porto Amboim",
  },
  {
    chaves: ["clube-vespa"],
    ficheiro: "imagens/instagram-C3qHQEnMJyW-1.jpg",
    conta: "@vespa_angola",
    publicacao: "https://www.instagram.com/p/C3qHQEnMJyW/",
    imagem: 1,
    data: "2024-02-22",
    descricao: "Grupo de Vespas na estrada, pilotos de capacete",
  },
  {
    chaves: ["scooters"],
    ficheiro: "imagens/instagram-C_kY30liZyR-2.jpg",
    conta: "@vespa_angola",
    publicacao: "https://www.instagram.com/p/C_kY30liZyR/",
    imagem: 2,
    data: "2024-09-06",
    descricao: "Vespa carregada para viagem, numa estrada ao pôr do sol",
  },
];
