/* ============================================================
   MOTOBOX — Fotografias reais das rotas (Wikimedia Commons)

   Só ficheiros com licença livre (CC BY, CC BY-SA, CC0 ou domínio
   público), escolhidos por mostrarem o próprio lugar. As licenças
   CC pedem o autor, a licença e a ligação: a página mostra-os por
   baixo de cada fotografia.

   As imagens carregam directamente do upload.wikimedia.org, nas
   larguras-padrão de miniatura do Commons (960, 1280 e 1920 px; as
   outras dão erro 400). Não passam pelo optimizador do Next: o
   Commons limita pedidos em rajada de servidores sem identificação
   (429), e o browser de cada visitante não tem esse problema.
   A primeira de cada lista é a capa.
   ============================================================ */

import type { Foto } from "@/lib/rotas-tipos";

// O tipo e o endereço de cada fotografia vivem em lib/rotas-tipos.ts (leve,
// para o browser); ficam aqui também para quem já os importava daqui.
export { urlCommons, urlFoto, type Foto, type LarguraCommons } from "@/lib/rotas-tipos";

const f = (
  arquivo: string,
  largura: number,
  altura: number,
  pagina: string,
  autor: string,
  licenca: string,
  licencaUrl: string,
  local: string,
  alt: string,
): Foto => ({ arquivo, largura, altura, pagina, autor, licenca, licencaUrl, local, alt });

export const FOTOS: Record<string, Foto[]> = {
  "serra-da-leba": [
    // Tem a ponta de um dedo, desfocada, no canto superior esquerdo: recorta-se pela direita.
    {
      ...f(
        "5/52/Serra_da_Leba-Road.jpg",
        3264,
        1836,
        "https://commons.wikimedia.org/wiki/File:Serra_da_Leba-Road.jpg",
        "Valmir144",
        "CC BY-SA 4.0",
        "https://creativecommons.org/licenses/by-sa/4.0",
        "Serra da Leba, curvas da estrada EN-280",
        "Estrada da Serra da Leba a descer a escarpa em curvas apertadas entre paredes de rocha e vegetação.",
      ),
      foco: "85% 60%",
    },
    f(
      "9/9d/Serra_da_Leba_Road%2C_Angola.jpg",
      960,
      717,
      "https://commons.wikimedia.org/wiki/File:Serra_da_Leba_Road,_Angola.jpg",
      "King9912",
      "CC BY-SA 4.0",
      "https://creativecommons.org/licenses/by-sa/4.0",
      "Serra da Leba, ziguezague visto do miradouro",
      "Vista do miradouro sobre o famoso ziguezague da estrada da Serra da Leba, encostado a uma grande falésia.",
    ),
    f(
      "8/86/Lubango-Namibe_landscape.jpg",
      2592,
      1944,
      "https://commons.wikimedia.org/wiki/File:Lubango-Namibe_landscape.jpg",
      "Erik Cleves Kristensen",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Serra da Leba, paisagem na estrada Lubango–Namibe",
      "Montanhas verdes e vale amplo sob céu com nuvens, na descida da Serra da Leba a caminho do Namibe.",
    ),
    f(
      "b/b1/Namib_desert_Angola.jpg",
      2592,
      1944,
      "https://commons.wikimedia.org/wiki/File:Namib_desert_Angola.jpg",
      "Erik Cleves Kristensen",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Deserto do Namibe, planície na estrada Lubango–Namibe",
      "Planície desértica plana e pedregosa com uma mesa de rocha no horizonte, já abaixo da serra.",
    ),
    f(
      "5/50/Lubango_sight.jpg",
      2592,
      1944,
      "https://commons.wikimedia.org/wiki/File:Lubango_sight.jpg",
      "Erik Kristensen",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Lubango, vista da cidade a partir da serra",
      "Encosta rochosa em primeiro plano e a cidade do Lubango espalhada pelo planalto ao fundo.",
    ),
  ],
  "tundavala": [
    f(
      "3/30/Tundavala_Gap.jpg",
      3264,
      2448,
      "https://commons.wikimedia.org/wiki/File:Tundavala_Gap.jpg",
      "tim kubacki",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Fenda da Tundavala",
      "Fenda da Tundavala, com falésias de rocha a abrir-se sobre um desfiladeiro profundo e céu limpo.",
    ),
    f(
      "2/2c/Tundavala_panorama.jpg",
      6476,
      1619,
      "https://commons.wikimedia.org/wiki/File:Tundavala_panorama.jpg",
      "SangeevP",
      "CC BY-SA 4.0",
      "https://creativecommons.org/licenses/by-sa/4.0",
      "Fenda da Tundavala, panorama da escarpa",
      "Panorama largo a partir da borda da Tundavala sobre a planície muito abaixo e a escarpa à direita.",
    ),
    f(
      "0/0e/Tundavala_Gap_sunset.jpg",
      3264,
      2448,
      "https://commons.wikimedia.org/wiki/File:Tundavala_Gap_sunset.jpg",
      "tim kubacki",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Tundavala ao nascer do sol",
      "Sol a nascer no horizonte sobre colinas, enquadrado por rochas escuras na Tundavala.",
    ),
    f(
      "1/1e/Lubango.jpg",
      2592,
      1944,
      "https://commons.wikimedia.org/wiki/File:Lubango.jpg",
      "Erik Cleves Kristensen",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Lubango, vista da cidade",
      "Vista alta da cidade do Lubango, com a malha urbana e o planalto sob céu nublado.",
    ),
    f(
      "2/2f/Cristo_Rei_Lubango.jpg",
      640,
      480,
      "https://commons.wikimedia.org/wiki/File:Cristo_Rei_Lubango.jpg",
      "ibnluanda",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Cristo Rei do Lubango",
      "Estátua branca do Cristo Rei de braços abertos sobre o pedestal, no alto da serra do Lubango.",
    ),
  ],
  "kalandula-e-pungo-andongo": [
    f(
      "6/63/Quedas-Kalandula_07_queda_LWS-2011-08_QD18_%28cropped%29.jpg",
      3925,
      1962,
      "https://commons.wikimedia.org/wiki/File:Quedas-Kalandula_07_queda_LWS-2011-08_QD18_(cropped).jpg",
      "L.Willms",
      "CC BY-SA 3.0",
      "https://creativecommons.org/licenses/by-sa/3.0",
      "Quedas de Kalandula, rio Lucala",
      "As Quedas de Kalandula em toda a largura, com várias cortinas de água a cair para o desfiladeiro.",
    ),
    f(
      "9/95/Kalandula_waterfalls_of_the_Lucala-River_in_Malange%2C_Angola.JPG",
      2272,
      1704,
      "https://commons.wikimedia.org/wiki/File:Kalandula_waterfalls_of_the_Lucala-River_in_Malange,_Angola.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Quedas de Kalandula, vista do miradouro",
      "Grande queda de água de Kalandula com spray branco e floresta verde no topo da escarpa.",
    ),
    f(
      "b/b7/Pungo_Andongo%2C_Malange%2C_Angola%2C_2008.JPG",
      2272,
      1704,
      "https://commons.wikimedia.org/wiki/File:Pungo_Andongo,_Malange,_Angola,_2008.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Pedras Negras de Pungo Andongo",
      "Picada de terra vermelha entre capim alto a caminho das enormes Pedras Negras de Pungo Andongo.",
    ),
    f(
      "9/94/Black_Stones_Pungo_Adongo.JPG",
      1600,
      1200,
      "https://commons.wikimedia.org/wiki/File:Black_Stones_Pungo_Adongo.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Pedras Negras de Pungo Andongo, rochedos",
      "Dois rochedos gigantes e escuros, com manchas de líquenes, a erguer-se do capim sob céu azul.",
    ),
    f(
      "6/61/Pungo_Andongo%2C_Malange%2C_Angola.JPG",
      2272,
      1704,
      "https://commons.wikimedia.org/wiki/File:Pungo_Andongo,_Malange,_Angola.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Pungo Andongo, estrada entre os rochedos",
      "Estrada de terra ladeada de capim alto, com grandes rochedos arredondados ao fundo.",
    ),
    f(
      "d/d6/Malanje_centro_2011-08_IMG1321.jpg",
      4000,
      2045,
      "https://commons.wikimedia.org/wiki/File:Malanje_centro_2011-08_IMG1321.jpg",
      "L.Willms",
      "CC BY 3.0",
      "https://creativecommons.org/licenses/by/3.0",
      "Malanje, centro da cidade",
      "Avenida larga e praça com palmeiras e edifícios no centro de Malanje.",
    ),
  ],
  "miradouro-da-lua": [
    f(
      "e/e3/Miradouro_da_Lua.jpg",
      2592,
      1944,
      "https://commons.wikimedia.org/wiki/File:Miradouro_da_Lua.jpg",
      "jlrsousa",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Miradouro da Lua",
      "Falésias erodidas em agulhas e paredes de tons ocre e vermelho no Miradouro da Lua.",
    ),
    f(
      "4/4f/Moon_view.jpg",
      3264,
      2448,
      "https://commons.wikimedia.org/wiki/File:Moon_view.jpg",
      "Patyfessora",
      "CC BY-SA 4.0",
      "https://creativecommons.org/licenses/by-sa/4.0",
      "Miradouro da Lua, vista da borda",
      "Borda vermelha da falésia e o vale de formações erodidas em tons claros, vistos do miradouro.",
    ),
    f(
      "b/b2/Miradouro_da_Lua_%28Angola%29.jpg",
      2272,
      1704,
      "https://commons.wikimedia.org/wiki/File:Miradouro_da_Lua_(Angola).jpg",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Miradouro da Lua, falésias vermelhas",
      "Falésias de terra vermelha e laranja a descer em ravinas, com mato no topo.",
    ),
    f(
      "1/1c/Bridge_over_Kwanza_River.jpg",
      3264,
      2448,
      "https://commons.wikimedia.org/wiki/File:Bridge_over_Kwanza_River.jpg",
      "Patyfessora",
      "CC BY-SA 4.0",
      "https://creativecommons.org/licenses/by-sa/4.0",
      "Ponte sobre o rio Kwanza",
      "Ponte de tirantes sobre o rio Kwanza vista de um barco, com a esteira na água.",
    ),
    f(
      "c/c0/Kwanza_River.jpg",
      3264,
      2448,
      "https://commons.wikimedia.org/wiki/File:Kwanza_River.jpg",
      "Patyfessora",
      "CC BY-SA 4.0",
      "https://creativecommons.org/licenses/by-sa/4.0",
      "Rio Kwanza, vista de barco",
      "Proa de um barco a subir o rio Kwanza, entre margens de vegetação densa.",
    ),
    f(
      "c/c7/Marginal_de_Luanda_HD_Dji_Mavic_3_Classic_-_By_D%C3%A9lcio_Geovany_Borges.jpg",
      5280,
      3956,
      "https://commons.wikimedia.org/wiki/File:Marginal_de_Luanda_HD_Dji_Mavic_3_Classic_-_By_D%C3%A9lcio_Geovany_Borges.jpg",
      "Iamdelcioborges",
      "CC BY 4.0",
      "https://creativecommons.org/licenses/by/4.0",
      "Marginal de Luanda (ponto de partida)",
      "Vista aérea da baía e da Marginal de Luanda, com a fortaleza e os prédios da cidade.",
    ),
  ],
  "cabo-ledo-e-quicama": [
    f(
      "3/38/Cabo_Ledo%2C_Bengo_province%2C_Angola.JPG",
      1600,
      1200,
      "https://commons.wikimedia.org/wiki/File:Cabo_Ledo,_Bengo_province,_Angola.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Cabo Ledo, costa e baía",
      "Costa rochosa de Cabo Ledo com ondas a rebentar, um penedo no mar e falésias verdes ao fundo.",
    ),
    f(
      "f/f0/PC-24-AG-D1-HCO-540.jpg",
      4608,
      3456,
      "https://commons.wikimedia.org/wiki/File:PC-24-AG-D1-HCO-540.jpg",
      "Hamilton Alberto",
      "CC BY 4.0",
      "https://creativecommons.org/licenses/by/4.0",
      "Baía de Cabo Ledo, praia",
      "Praia de areia dourada em Cabo Ledo com barracas de sombra e falésias ao fundo.",
    ),
    f(
      "7/75/Cabo_Ledo_beach%2C_Angola_02.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Cabo_Ledo_beach,_Angola_02.jpg",
      "Felipe Miguel from Curitiba, Brazil",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Praia de Cabo Ledo",
      "Areal largo e vazio de Cabo Ledo, com o mar calmo e as falésias ao longe.",
    ),
    f(
      "c/c8/Surfing_in_Cabo_Ledo_beach%2C_Angola.jpg",
      1272,
      954,
      "https://commons.wikimedia.org/wiki/File:Surfing_in_Cabo_Ledo_beach,_Angola.jpg",
      "Felipe Miguel from Curitiba, Brazil",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Cabo Ledo, ondas de surf",
      "Surfistas a apanhar uma onda em Cabo Ledo, com a linha de falésias no horizonte.",
    ),
    f(
      "a/af/Kissama_Matebeira.jpg",
      2304,
      1728,
      "https://commons.wikimedia.org/wiki/File:Kissama_Matebeira.jpg",
      "Zorglub",
      "CC BY 3.0",
      "https://creativecommons.org/licenses/by/3.0",
      "Parque Nacional da Quiçama, matebeira",
      "Palmeira matebeira em primeiro plano e savana verde ondulada do Parque Nacional da Quiçama.",
    ),
    f(
      "e/e2/Church_of_Muxima%2C_pilgrimage_site%2C_Bengo_province.JPG",
      4000,
      3000,
      "https://commons.wikimedia.org/wiki/File:Church_of_Muxima,_pilgrimage_site,_Bengo_province.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Igreja de Nossa Senhora da Muxima",
      "Fachada branca da igreja de Nossa Senhora da Muxima, local de peregrinação, sob céu azul.",
    ),
  ],
  "deserto-do-namibe": [
    f(
      "a/a8/Parque_Nacional_do_lona_2.jpg",
      4329,
      2197,
      "https://commons.wikimedia.org/wiki/File:Parque_Nacional_do_lona_2.jpg",
      "Edward Middleton",
      "CC BY-SA 4.0",
      "https://creativecommons.org/licenses/by-sa/4.0",
      "Parque Nacional do Iona, dunas",
      "Imensidão de areia e dunas baixas no Parque Nacional do Iona, com jipes pequenos ao longe.",
    ),
    f(
      "6/6c/Welwitschia_in_the_Namibe_desert.JPG",
      4000,
      3000,
      "https://commons.wikimedia.org/wiki/File:Welwitschia_in_the_Namibe_desert.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Welwitschia mirabilis no deserto do Namibe",
      "Uma welwitschia com as folhas compridas espalhadas no chão de areia e cascalho do deserto do Namibe.",
    ),
    f(
      "d/d0/Stone_Arch_%2819589801062%29.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Stone_Arch_(19589801062).jpg",
      "David Stanley from Nanaimo, Canada",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Lagoa do Arco, arco de pedra",
      "Arco natural de rocha clara junto à Lagoa do Arco, rodeado de vegetação seca.",
    ),
    f(
      "4/4e/Lago_do_Arco_do_Carvalhao_%2819417878100%29.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Lago_do_Arco_do_Carvalhao_(19417878100).jpg",
      "David Stanley from Nanaimo, Canada",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Lagoa do Arco",
      "A Lagoa do Arco vista do alto das rochas, com o leito verde e escarpas de arenito à volta.",
    ),
    f(
      "9/91/Mini_oasis_in_the_namibe_desert%2C_Angola.JPG",
      4000,
      3000,
      "https://commons.wikimedia.org/wiki/File:Mini_oasis_in_the_namibe_desert,_Angola.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Oásis no deserto do Namibe",
      "Pequeno oásis de água com plantas aquáticas entre rochas claras de arenito no deserto do Namibe.",
    ),
    f(
      "b/b2/Church_in_Tombua%2C_Namibe%2C_Angola.JPG",
      1600,
      1200,
      "https://commons.wikimedia.org/wiki/File:Church_in_Tombua,_Namibe,_Angola.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Tômbwa, igreja",
      "Igreja amarela com torre sineira em Tômbwa, sob céu azul.",
    ),
    f(
      "9/9f/Namibe_Waterfront_%2819432713306%29.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Namibe_Waterfront_(19432713306).jpg",
      "David Stanley from Nanaimo, Canada",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Moçâmedes, avenida marginal",
      "Avenida marginal de Moçâmedes a contornar a baía azul, vista do alto.",
    ),
  ],
  "costa-de-benguela": [
    f(
      "8/8f/Caotinha_Benguela_Angola.jpg",
      2272,
      1704,
      "https://commons.wikimedia.org/wiki/File:Caotinha_Benguela_Angola.jpg",
      "F Mira",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Caotinha, falésias ao fim da tarde",
      "Falésia dourada pela luz do fim da tarde na Caotinha, com uma casa no topo e o mar calmo em baixo.",
    ),
    f(
      "7/71/Beach_of_Coatinha_in_Benguela%2C_Angola.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Beach_of_Coatinha_in_Benguela,_Angola.jpg",
      "jlrsousa",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Caotinha, falésias para norte",
      "Mar azul e falésias altas a recortar a costa a norte da Caotinha, com um barco pequeno.",
    ),
    f(
      "9/97/Prainha%2C_Caotinha%2C_Benguela_%283011186226%29.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Prainha,_Caotinha,_Benguela_(3011186226).jpg",
      "jlrsousa",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Prainha da Caotinha",
      "Pequena praia de enseada na Caotinha, com água transparente e encosta rochosa por cima.",
    ),
    f(
      "7/70/Praia_Morena_%2819699922970%29.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Praia_Morena_(19699922970).jpg",
      "David Stanley from Nanaimo, Canada",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Benguela, Praia Morena",
      "Areal comprido e quase vazio da Praia Morena em Benguela, sob céu azul.",
    ),
    f(
      "e/e6/Igreja_Benguela%2C_Angola.jpg",
      1805,
      1317,
      "https://commons.wikimedia.org/wiki/File:Igreja_Benguela,_Angola.jpg",
      "F H Mira",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Benguela, igreja histórica",
      "Igreja colonial de duas torres em Benguela, iluminada pela luz quente do fim do dia.",
    ),
    f(
      "5/53/Restinga_Peninsula_%2818996958243%29.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Restinga_Peninsula_(18996958243).jpg",
      "David Stanley from Nanaimo, Canada",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Restinga do Lobito",
      "A Restinga do Lobito, faixa de areia com árvores, vista do outro lado da baía.",
    ),
    f(
      "0/04/Igreja_da_Arr%C3%A1bida_in_Lobito_-_Angola_2015.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Igreja_da_Arr%C3%A1bida_in_Lobito_-_Angola_2015.jpg",
      "David Stanley from Nanaimo, Canada",
      "CC BY 2.0",
      "https://creativecommons.org/licenses/by/2.0",
      "Lobito, Igreja da Arrábida na Restinga",
      "Igreja branca da Arrábida na Restinga do Lobito, vista do outro lado da água.",
    ),
  ],
  "estrada-da-costa": [
    f(
      "b/bd/Marginal_of_Namibe.JPG",
      4000,
      3000,
      "https://commons.wikimedia.org/wiki/File:Marginal_of_Namibe.JPG",
      "Paulo César Santos",
      "CC0",
      "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "Moçâmedes, estrada marginal junto à baía",
      "Estrada marginal de Moçâmedes a acompanhar a baía cheia de barcos, com o porto ao fundo.",
    ),
    f(
      "6/6a/Bridge_crossing_Cuanza_River%2C_Angola.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Bridge_crossing_Cuanza_River,_Angola.jpg",
      "jlrsousa",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Estrada Luanda–Lobito, ponte do Kwanza",
      "Estrada asfaltada entre palmeiras a chegar à ponte sobre o rio Kwanza, com uma carrinha à frente.",
    ),
    f(
      "0/0b/Cabo_Ledo_beach%2C_Angola_01.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Cabo_Ledo_beach,_Angola_01.jpg",
      "Felipe Miguel from Curitiba, Brazil",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Cabo Ledo, praia e falésias",
      "Praia de Cabo Ledo com rochas na areia, mar e falésias ao fundo.",
    ),
    f(
      "9/99/Porto_Amboim_-_Praia_dos_pescadores.jpg",
      2048,
      1536,
      "https://commons.wikimedia.org/wiki/File:Porto_Amboim_-_Praia_dos_pescadores.jpg",
      "INilton",
      "CC BY-SA 4.0",
      "https://creativecommons.org/licenses/by-sa/4.0",
      "Porto Amboim, Praia dos Pescadores",
      "Praia dos Pescadores a norte de Porto Amboim, com mar turquesa e barcos na baía.",
    ),
    f(
      "f/f5/Gorge_of_Rio_Cubal%2C_Angola.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Gorge_of_Rio_Cubal,_Angola.jpg",
      "jlrsousa",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Garganta do rio Cubal, perto do Sumbe",
      "Rio Cubal a correr numa garganta entre paredes de rocha e palmeiras, perto do Sumbe.",
    ),
    f(
      "a/a2/Beach_in_Sumbe%2C_Angola.jpg",
      1024,
      768,
      "https://commons.wikimedia.org/wiki/File:Beach_in_Sumbe,_Angola.jpg",
      "jlrsousa",
      "CC BY-SA 2.0",
      "https://creativecommons.org/licenses/by-sa/2.0",
      "Sumbe, praia",
      "Praia do Sumbe com ondas suaves, gente ao longe e um velho pontão no mar.",
    ),
    f(
      "8/8c/Catumbela_noite.JPG",
      1500,
      1125,
      "https://commons.wikimedia.org/wiki/File:Catumbela_noite.JPG",
      "ME",
      "Domínio público",
      "https://commons.wikimedia.org/wiki/File:Catumbela_noite.JPG",
      "Catumbela, ponte entre Lobito e Benguela",
      "Ponte de tirantes da Catumbela iluminada ao anoitecer.",
    ),
  ],
};
